
/* !!! This is code generated by Prisma. Do not edit directly. !!! */
/* eslint-disable */
// biome-ignore-all lint: generated file
// @ts-nocheck 
/*
 * This file exports the `employee` model and its related types.
 *
 * 🟢 You can import this file directly.
 */
import type * as runtime from "@prisma/client/runtime/client"
import type * as $Enums from "../enums.ts"
import type * as Prisma from "../internal/prismaNamespace.ts"

/**
 * Model employee
 * 
 */
export type employeeModel = runtime.Types.Result.DefaultSelection<Prisma.$employeePayload>

export type AggregateEmployee = {
  _count: EmployeeCountAggregateOutputType | null
  _avg: EmployeeAvgAggregateOutputType | null
  _sum: EmployeeSumAggregateOutputType | null
  _min: EmployeeMinAggregateOutputType | null
  _max: EmployeeMaxAggregateOutputType | null
}

export type EmployeeAvgAggregateOutputType = {
  ID: number | null
}

export type EmployeeSumAggregateOutputType = {
  ID: number | null
}

export type EmployeeMinAggregateOutputType = {
  ID: number | null
  Name: string | null
}

export type EmployeeMaxAggregateOutputType = {
  ID: number | null
  Name: string | null
}

export type EmployeeCountAggregateOutputType = {
  ID: number
  Name: number
  _all: number
}


export type EmployeeAvgAggregateInputType = {
  ID?: true
}

export type EmployeeSumAggregateInputType = {
  ID?: true
}

export type EmployeeMinAggregateInputType = {
  ID?: true
  Name?: true
}

export type EmployeeMaxAggregateInputType = {
  ID?: true
  Name?: true
}

export type EmployeeCountAggregateInputType = {
  ID?: true
  Name?: true
  _all?: true
}

export type EmployeeAggregateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Filter which employee to aggregate.
   */
  where?: Prisma.employeeWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of employees to fetch.
   */
  orderBy?: Prisma.employeeOrderByWithRelationInput | Prisma.employeeOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the start position
   */
  cursor?: Prisma.employeeWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` employees from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` employees.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Count returned employees
  **/
  _count?: true | EmployeeCountAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to average
  **/
  _avg?: EmployeeAvgAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to sum
  **/
  _sum?: EmployeeSumAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to find the minimum value
  **/
  _min?: EmployeeMinAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to find the maximum value
  **/
  _max?: EmployeeMaxAggregateInputType
}

export type GetEmployeeAggregateType<T extends EmployeeAggregateArgs> = {
      [P in keyof T & keyof AggregateEmployee]: P extends '_count' | 'count'
    ? T[P] extends true
      ? number
      : Prisma.GetScalarType<T[P], AggregateEmployee[P]>
    : Prisma.GetScalarType<T[P], AggregateEmployee[P]>
}




export type employeeGroupByArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  where?: Prisma.employeeWhereInput
  orderBy?: Prisma.employeeOrderByWithAggregationInput | Prisma.employeeOrderByWithAggregationInput[]
  by: Prisma.EmployeeScalarFieldEnum[] | Prisma.EmployeeScalarFieldEnum
  having?: Prisma.employeeScalarWhereWithAggregatesInput
  take?: number
  skip?: number
  _count?: EmployeeCountAggregateInputType | true
  _avg?: EmployeeAvgAggregateInputType
  _sum?: EmployeeSumAggregateInputType
  _min?: EmployeeMinAggregateInputType
  _max?: EmployeeMaxAggregateInputType
}

export type EmployeeGroupByOutputType = {
  ID: number
  Name: string
  _count: EmployeeCountAggregateOutputType | null
  _avg: EmployeeAvgAggregateOutputType | null
  _sum: EmployeeSumAggregateOutputType | null
  _min: EmployeeMinAggregateOutputType | null
  _max: EmployeeMaxAggregateOutputType | null
}

export type GetEmployeeGroupByPayload<T extends employeeGroupByArgs> = Prisma.PrismaPromise<
  Array<
    Prisma.PickEnumerable<EmployeeGroupByOutputType, T['by']> &
      {
        [P in ((keyof T) & (keyof EmployeeGroupByOutputType))]: P extends '_count'
          ? T[P] extends boolean
            ? number
            : Prisma.GetScalarType<T[P], EmployeeGroupByOutputType[P]>
          : Prisma.GetScalarType<T[P], EmployeeGroupByOutputType[P]>
      }
    >
  >



export type employeeWhereInput = {
  AND?: Prisma.employeeWhereInput | Prisma.employeeWhereInput[]
  OR?: Prisma.employeeWhereInput[]
  NOT?: Prisma.employeeWhereInput | Prisma.employeeWhereInput[]
  ID?: Prisma.IntFilter<"employee"> | number
  Name?: Prisma.StringFilter<"employee"> | string
  employeecheckin?: Prisma.EmployeecheckinListRelationFilter
  employeedepartment?: Prisma.EmployeedepartmentListRelationFilter
  employeeinfo?: Prisma.EmployeeinfoListRelationFilter
  employeeskill?: Prisma.EmployeeskillListRelationFilter
}

export type employeeOrderByWithRelationInput = {
  ID?: Prisma.SortOrder
  Name?: Prisma.SortOrder
  employeecheckin?: Prisma.employeecheckinOrderByRelationAggregateInput
  employeedepartment?: Prisma.employeedepartmentOrderByRelationAggregateInput
  employeeinfo?: Prisma.employeeinfoOrderByRelationAggregateInput
  employeeskill?: Prisma.employeeskillOrderByRelationAggregateInput
  _relevance?: Prisma.employeeOrderByRelevanceInput
}

export type employeeWhereUniqueInput = Prisma.AtLeast<{
  ID?: number
  AND?: Prisma.employeeWhereInput | Prisma.employeeWhereInput[]
  OR?: Prisma.employeeWhereInput[]
  NOT?: Prisma.employeeWhereInput | Prisma.employeeWhereInput[]
  Name?: Prisma.StringFilter<"employee"> | string
  employeecheckin?: Prisma.EmployeecheckinListRelationFilter
  employeedepartment?: Prisma.EmployeedepartmentListRelationFilter
  employeeinfo?: Prisma.EmployeeinfoListRelationFilter
  employeeskill?: Prisma.EmployeeskillListRelationFilter
}, "ID">

export type employeeOrderByWithAggregationInput = {
  ID?: Prisma.SortOrder
  Name?: Prisma.SortOrder
  _count?: Prisma.employeeCountOrderByAggregateInput
  _avg?: Prisma.employeeAvgOrderByAggregateInput
  _max?: Prisma.employeeMaxOrderByAggregateInput
  _min?: Prisma.employeeMinOrderByAggregateInput
  _sum?: Prisma.employeeSumOrderByAggregateInput
}

export type employeeScalarWhereWithAggregatesInput = {
  AND?: Prisma.employeeScalarWhereWithAggregatesInput | Prisma.employeeScalarWhereWithAggregatesInput[]
  OR?: Prisma.employeeScalarWhereWithAggregatesInput[]
  NOT?: Prisma.employeeScalarWhereWithAggregatesInput | Prisma.employeeScalarWhereWithAggregatesInput[]
  ID?: Prisma.IntWithAggregatesFilter<"employee"> | number
  Name?: Prisma.StringWithAggregatesFilter<"employee"> | string
}

export type employeeCreateInput = {
  Name: string
  employeecheckin?: Prisma.employeecheckinCreateNestedManyWithoutEmployeeInput
  employeedepartment?: Prisma.employeedepartmentCreateNestedManyWithoutEmployeeInput
  employeeinfo?: Prisma.employeeinfoCreateNestedManyWithoutEmployeeInput
  employeeskill?: Prisma.employeeskillCreateNestedManyWithoutEmployeeInput
}

export type employeeUncheckedCreateInput = {
  ID?: number
  Name: string
  employeecheckin?: Prisma.employeecheckinUncheckedCreateNestedManyWithoutEmployeeInput
  employeedepartment?: Prisma.employeedepartmentUncheckedCreateNestedManyWithoutEmployeeInput
  employeeinfo?: Prisma.employeeinfoUncheckedCreateNestedManyWithoutEmployeeInput
  employeeskill?: Prisma.employeeskillUncheckedCreateNestedManyWithoutEmployeeInput
}

export type employeeUpdateInput = {
  Name?: Prisma.StringFieldUpdateOperationsInput | string
  employeecheckin?: Prisma.employeecheckinUpdateManyWithoutEmployeeNestedInput
  employeedepartment?: Prisma.employeedepartmentUpdateManyWithoutEmployeeNestedInput
  employeeinfo?: Prisma.employeeinfoUpdateManyWithoutEmployeeNestedInput
  employeeskill?: Prisma.employeeskillUpdateManyWithoutEmployeeNestedInput
}

export type employeeUncheckedUpdateInput = {
  ID?: Prisma.IntFieldUpdateOperationsInput | number
  Name?: Prisma.StringFieldUpdateOperationsInput | string
  employeecheckin?: Prisma.employeecheckinUncheckedUpdateManyWithoutEmployeeNestedInput
  employeedepartment?: Prisma.employeedepartmentUncheckedUpdateManyWithoutEmployeeNestedInput
  employeeinfo?: Prisma.employeeinfoUncheckedUpdateManyWithoutEmployeeNestedInput
  employeeskill?: Prisma.employeeskillUncheckedUpdateManyWithoutEmployeeNestedInput
}

export type employeeCreateManyInput = {
  ID?: number
  Name: string
}

export type employeeUpdateManyMutationInput = {
  Name?: Prisma.StringFieldUpdateOperationsInput | string
}

export type employeeUncheckedUpdateManyInput = {
  ID?: Prisma.IntFieldUpdateOperationsInput | number
  Name?: Prisma.StringFieldUpdateOperationsInput | string
}

export type employeeOrderByRelevanceInput = {
  fields: Prisma.employeeOrderByRelevanceFieldEnum | Prisma.employeeOrderByRelevanceFieldEnum[]
  sort: Prisma.SortOrder
  search: string
}

export type employeeCountOrderByAggregateInput = {
  ID?: Prisma.SortOrder
  Name?: Prisma.SortOrder
}

export type employeeAvgOrderByAggregateInput = {
  ID?: Prisma.SortOrder
}

export type employeeMaxOrderByAggregateInput = {
  ID?: Prisma.SortOrder
  Name?: Prisma.SortOrder
}

export type employeeMinOrderByAggregateInput = {
  ID?: Prisma.SortOrder
  Name?: Prisma.SortOrder
}

export type employeeSumOrderByAggregateInput = {
  ID?: Prisma.SortOrder
}

export type EmployeeScalarRelationFilter = {
  is?: Prisma.employeeWhereInput
  isNot?: Prisma.employeeWhereInput
}

export type employeeCreateNestedOneWithoutEmployeecheckinInput = {
  create?: Prisma.XOR<Prisma.employeeCreateWithoutEmployeecheckinInput, Prisma.employeeUncheckedCreateWithoutEmployeecheckinInput>
  connectOrCreate?: Prisma.employeeCreateOrConnectWithoutEmployeecheckinInput
  connect?: Prisma.employeeWhereUniqueInput
}

export type employeeUpdateOneRequiredWithoutEmployeecheckinNestedInput = {
  create?: Prisma.XOR<Prisma.employeeCreateWithoutEmployeecheckinInput, Prisma.employeeUncheckedCreateWithoutEmployeecheckinInput>
  connectOrCreate?: Prisma.employeeCreateOrConnectWithoutEmployeecheckinInput
  upsert?: Prisma.employeeUpsertWithoutEmployeecheckinInput
  connect?: Prisma.employeeWhereUniqueInput
  update?: Prisma.XOR<Prisma.XOR<Prisma.employeeUpdateToOneWithWhereWithoutEmployeecheckinInput, Prisma.employeeUpdateWithoutEmployeecheckinInput>, Prisma.employeeUncheckedUpdateWithoutEmployeecheckinInput>
}

export type employeeCreateNestedOneWithoutEmployeedepartmentInput = {
  create?: Prisma.XOR<Prisma.employeeCreateWithoutEmployeedepartmentInput, Prisma.employeeUncheckedCreateWithoutEmployeedepartmentInput>
  connectOrCreate?: Prisma.employeeCreateOrConnectWithoutEmployeedepartmentInput
  connect?: Prisma.employeeWhereUniqueInput
}

export type employeeUpdateOneRequiredWithoutEmployeedepartmentNestedInput = {
  create?: Prisma.XOR<Prisma.employeeCreateWithoutEmployeedepartmentInput, Prisma.employeeUncheckedCreateWithoutEmployeedepartmentInput>
  connectOrCreate?: Prisma.employeeCreateOrConnectWithoutEmployeedepartmentInput
  upsert?: Prisma.employeeUpsertWithoutEmployeedepartmentInput
  connect?: Prisma.employeeWhereUniqueInput
  update?: Prisma.XOR<Prisma.XOR<Prisma.employeeUpdateToOneWithWhereWithoutEmployeedepartmentInput, Prisma.employeeUpdateWithoutEmployeedepartmentInput>, Prisma.employeeUncheckedUpdateWithoutEmployeedepartmentInput>
}

export type employeeCreateNestedOneWithoutEmployeeinfoInput = {
  create?: Prisma.XOR<Prisma.employeeCreateWithoutEmployeeinfoInput, Prisma.employeeUncheckedCreateWithoutEmployeeinfoInput>
  connectOrCreate?: Prisma.employeeCreateOrConnectWithoutEmployeeinfoInput
  connect?: Prisma.employeeWhereUniqueInput
}

export type employeeUpdateOneRequiredWithoutEmployeeinfoNestedInput = {
  create?: Prisma.XOR<Prisma.employeeCreateWithoutEmployeeinfoInput, Prisma.employeeUncheckedCreateWithoutEmployeeinfoInput>
  connectOrCreate?: Prisma.employeeCreateOrConnectWithoutEmployeeinfoInput
  upsert?: Prisma.employeeUpsertWithoutEmployeeinfoInput
  connect?: Prisma.employeeWhereUniqueInput
  update?: Prisma.XOR<Prisma.XOR<Prisma.employeeUpdateToOneWithWhereWithoutEmployeeinfoInput, Prisma.employeeUpdateWithoutEmployeeinfoInput>, Prisma.employeeUncheckedUpdateWithoutEmployeeinfoInput>
}

export type employeeCreateNestedOneWithoutEmployeeskillInput = {
  create?: Prisma.XOR<Prisma.employeeCreateWithoutEmployeeskillInput, Prisma.employeeUncheckedCreateWithoutEmployeeskillInput>
  connectOrCreate?: Prisma.employeeCreateOrConnectWithoutEmployeeskillInput
  connect?: Prisma.employeeWhereUniqueInput
}

export type employeeUpdateOneRequiredWithoutEmployeeskillNestedInput = {
  create?: Prisma.XOR<Prisma.employeeCreateWithoutEmployeeskillInput, Prisma.employeeUncheckedCreateWithoutEmployeeskillInput>
  connectOrCreate?: Prisma.employeeCreateOrConnectWithoutEmployeeskillInput
  upsert?: Prisma.employeeUpsertWithoutEmployeeskillInput
  connect?: Prisma.employeeWhereUniqueInput
  update?: Prisma.XOR<Prisma.XOR<Prisma.employeeUpdateToOneWithWhereWithoutEmployeeskillInput, Prisma.employeeUpdateWithoutEmployeeskillInput>, Prisma.employeeUncheckedUpdateWithoutEmployeeskillInput>
}

export type employeeCreateWithoutEmployeecheckinInput = {
  Name: string
  employeedepartment?: Prisma.employeedepartmentCreateNestedManyWithoutEmployeeInput
  employeeinfo?: Prisma.employeeinfoCreateNestedManyWithoutEmployeeInput
  employeeskill?: Prisma.employeeskillCreateNestedManyWithoutEmployeeInput
}

export type employeeUncheckedCreateWithoutEmployeecheckinInput = {
  ID?: number
  Name: string
  employeedepartment?: Prisma.employeedepartmentUncheckedCreateNestedManyWithoutEmployeeInput
  employeeinfo?: Prisma.employeeinfoUncheckedCreateNestedManyWithoutEmployeeInput
  employeeskill?: Prisma.employeeskillUncheckedCreateNestedManyWithoutEmployeeInput
}

export type employeeCreateOrConnectWithoutEmployeecheckinInput = {
  where: Prisma.employeeWhereUniqueInput
  create: Prisma.XOR<Prisma.employeeCreateWithoutEmployeecheckinInput, Prisma.employeeUncheckedCreateWithoutEmployeecheckinInput>
}

export type employeeUpsertWithoutEmployeecheckinInput = {
  update: Prisma.XOR<Prisma.employeeUpdateWithoutEmployeecheckinInput, Prisma.employeeUncheckedUpdateWithoutEmployeecheckinInput>
  create: Prisma.XOR<Prisma.employeeCreateWithoutEmployeecheckinInput, Prisma.employeeUncheckedCreateWithoutEmployeecheckinInput>
  where?: Prisma.employeeWhereInput
}

export type employeeUpdateToOneWithWhereWithoutEmployeecheckinInput = {
  where?: Prisma.employeeWhereInput
  data: Prisma.XOR<Prisma.employeeUpdateWithoutEmployeecheckinInput, Prisma.employeeUncheckedUpdateWithoutEmployeecheckinInput>
}

export type employeeUpdateWithoutEmployeecheckinInput = {
  Name?: Prisma.StringFieldUpdateOperationsInput | string
  employeedepartment?: Prisma.employeedepartmentUpdateManyWithoutEmployeeNestedInput
  employeeinfo?: Prisma.employeeinfoUpdateManyWithoutEmployeeNestedInput
  employeeskill?: Prisma.employeeskillUpdateManyWithoutEmployeeNestedInput
}

export type employeeUncheckedUpdateWithoutEmployeecheckinInput = {
  ID?: Prisma.IntFieldUpdateOperationsInput | number
  Name?: Prisma.StringFieldUpdateOperationsInput | string
  employeedepartment?: Prisma.employeedepartmentUncheckedUpdateManyWithoutEmployeeNestedInput
  employeeinfo?: Prisma.employeeinfoUncheckedUpdateManyWithoutEmployeeNestedInput
  employeeskill?: Prisma.employeeskillUncheckedUpdateManyWithoutEmployeeNestedInput
}

export type employeeCreateWithoutEmployeedepartmentInput = {
  Name: string
  employeecheckin?: Prisma.employeecheckinCreateNestedManyWithoutEmployeeInput
  employeeinfo?: Prisma.employeeinfoCreateNestedManyWithoutEmployeeInput
  employeeskill?: Prisma.employeeskillCreateNestedManyWithoutEmployeeInput
}

export type employeeUncheckedCreateWithoutEmployeedepartmentInput = {
  ID?: number
  Name: string
  employeecheckin?: Prisma.employeecheckinUncheckedCreateNestedManyWithoutEmployeeInput
  employeeinfo?: Prisma.employeeinfoUncheckedCreateNestedManyWithoutEmployeeInput
  employeeskill?: Prisma.employeeskillUncheckedCreateNestedManyWithoutEmployeeInput
}

export type employeeCreateOrConnectWithoutEmployeedepartmentInput = {
  where: Prisma.employeeWhereUniqueInput
  create: Prisma.XOR<Prisma.employeeCreateWithoutEmployeedepartmentInput, Prisma.employeeUncheckedCreateWithoutEmployeedepartmentInput>
}

export type employeeUpsertWithoutEmployeedepartmentInput = {
  update: Prisma.XOR<Prisma.employeeUpdateWithoutEmployeedepartmentInput, Prisma.employeeUncheckedUpdateWithoutEmployeedepartmentInput>
  create: Prisma.XOR<Prisma.employeeCreateWithoutEmployeedepartmentInput, Prisma.employeeUncheckedCreateWithoutEmployeedepartmentInput>
  where?: Prisma.employeeWhereInput
}

export type employeeUpdateToOneWithWhereWithoutEmployeedepartmentInput = {
  where?: Prisma.employeeWhereInput
  data: Prisma.XOR<Prisma.employeeUpdateWithoutEmployeedepartmentInput, Prisma.employeeUncheckedUpdateWithoutEmployeedepartmentInput>
}

export type employeeUpdateWithoutEmployeedepartmentInput = {
  Name?: Prisma.StringFieldUpdateOperationsInput | string
  employeecheckin?: Prisma.employeecheckinUpdateManyWithoutEmployeeNestedInput
  employeeinfo?: Prisma.employeeinfoUpdateManyWithoutEmployeeNestedInput
  employeeskill?: Prisma.employeeskillUpdateManyWithoutEmployeeNestedInput
}

export type employeeUncheckedUpdateWithoutEmployeedepartmentInput = {
  ID?: Prisma.IntFieldUpdateOperationsInput | number
  Name?: Prisma.StringFieldUpdateOperationsInput | string
  employeecheckin?: Prisma.employeecheckinUncheckedUpdateManyWithoutEmployeeNestedInput
  employeeinfo?: Prisma.employeeinfoUncheckedUpdateManyWithoutEmployeeNestedInput
  employeeskill?: Prisma.employeeskillUncheckedUpdateManyWithoutEmployeeNestedInput
}

export type employeeCreateWithoutEmployeeinfoInput = {
  Name: string
  employeecheckin?: Prisma.employeecheckinCreateNestedManyWithoutEmployeeInput
  employeedepartment?: Prisma.employeedepartmentCreateNestedManyWithoutEmployeeInput
  employeeskill?: Prisma.employeeskillCreateNestedManyWithoutEmployeeInput
}

export type employeeUncheckedCreateWithoutEmployeeinfoInput = {
  ID?: number
  Name: string
  employeecheckin?: Prisma.employeecheckinUncheckedCreateNestedManyWithoutEmployeeInput
  employeedepartment?: Prisma.employeedepartmentUncheckedCreateNestedManyWithoutEmployeeInput
  employeeskill?: Prisma.employeeskillUncheckedCreateNestedManyWithoutEmployeeInput
}

export type employeeCreateOrConnectWithoutEmployeeinfoInput = {
  where: Prisma.employeeWhereUniqueInput
  create: Prisma.XOR<Prisma.employeeCreateWithoutEmployeeinfoInput, Prisma.employeeUncheckedCreateWithoutEmployeeinfoInput>
}

export type employeeUpsertWithoutEmployeeinfoInput = {
  update: Prisma.XOR<Prisma.employeeUpdateWithoutEmployeeinfoInput, Prisma.employeeUncheckedUpdateWithoutEmployeeinfoInput>
  create: Prisma.XOR<Prisma.employeeCreateWithoutEmployeeinfoInput, Prisma.employeeUncheckedCreateWithoutEmployeeinfoInput>
  where?: Prisma.employeeWhereInput
}

export type employeeUpdateToOneWithWhereWithoutEmployeeinfoInput = {
  where?: Prisma.employeeWhereInput
  data: Prisma.XOR<Prisma.employeeUpdateWithoutEmployeeinfoInput, Prisma.employeeUncheckedUpdateWithoutEmployeeinfoInput>
}

export type employeeUpdateWithoutEmployeeinfoInput = {
  Name?: Prisma.StringFieldUpdateOperationsInput | string
  employeecheckin?: Prisma.employeecheckinUpdateManyWithoutEmployeeNestedInput
  employeedepartment?: Prisma.employeedepartmentUpdateManyWithoutEmployeeNestedInput
  employeeskill?: Prisma.employeeskillUpdateManyWithoutEmployeeNestedInput
}

export type employeeUncheckedUpdateWithoutEmployeeinfoInput = {
  ID?: Prisma.IntFieldUpdateOperationsInput | number
  Name?: Prisma.StringFieldUpdateOperationsInput | string
  employeecheckin?: Prisma.employeecheckinUncheckedUpdateManyWithoutEmployeeNestedInput
  employeedepartment?: Prisma.employeedepartmentUncheckedUpdateManyWithoutEmployeeNestedInput
  employeeskill?: Prisma.employeeskillUncheckedUpdateManyWithoutEmployeeNestedInput
}

export type employeeCreateWithoutEmployeeskillInput = {
  Name: string
  employeecheckin?: Prisma.employeecheckinCreateNestedManyWithoutEmployeeInput
  employeedepartment?: Prisma.employeedepartmentCreateNestedManyWithoutEmployeeInput
  employeeinfo?: Prisma.employeeinfoCreateNestedManyWithoutEmployeeInput
}

export type employeeUncheckedCreateWithoutEmployeeskillInput = {
  ID?: number
  Name: string
  employeecheckin?: Prisma.employeecheckinUncheckedCreateNestedManyWithoutEmployeeInput
  employeedepartment?: Prisma.employeedepartmentUncheckedCreateNestedManyWithoutEmployeeInput
  employeeinfo?: Prisma.employeeinfoUncheckedCreateNestedManyWithoutEmployeeInput
}

export type employeeCreateOrConnectWithoutEmployeeskillInput = {
  where: Prisma.employeeWhereUniqueInput
  create: Prisma.XOR<Prisma.employeeCreateWithoutEmployeeskillInput, Prisma.employeeUncheckedCreateWithoutEmployeeskillInput>
}

export type employeeUpsertWithoutEmployeeskillInput = {
  update: Prisma.XOR<Prisma.employeeUpdateWithoutEmployeeskillInput, Prisma.employeeUncheckedUpdateWithoutEmployeeskillInput>
  create: Prisma.XOR<Prisma.employeeCreateWithoutEmployeeskillInput, Prisma.employeeUncheckedCreateWithoutEmployeeskillInput>
  where?: Prisma.employeeWhereInput
}

export type employeeUpdateToOneWithWhereWithoutEmployeeskillInput = {
  where?: Prisma.employeeWhereInput
  data: Prisma.XOR<Prisma.employeeUpdateWithoutEmployeeskillInput, Prisma.employeeUncheckedUpdateWithoutEmployeeskillInput>
}

export type employeeUpdateWithoutEmployeeskillInput = {
  Name?: Prisma.StringFieldUpdateOperationsInput | string
  employeecheckin?: Prisma.employeecheckinUpdateManyWithoutEmployeeNestedInput
  employeedepartment?: Prisma.employeedepartmentUpdateManyWithoutEmployeeNestedInput
  employeeinfo?: Prisma.employeeinfoUpdateManyWithoutEmployeeNestedInput
}

export type employeeUncheckedUpdateWithoutEmployeeskillInput = {
  ID?: Prisma.IntFieldUpdateOperationsInput | number
  Name?: Prisma.StringFieldUpdateOperationsInput | string
  employeecheckin?: Prisma.employeecheckinUncheckedUpdateManyWithoutEmployeeNestedInput
  employeedepartment?: Prisma.employeedepartmentUncheckedUpdateManyWithoutEmployeeNestedInput
  employeeinfo?: Prisma.employeeinfoUncheckedUpdateManyWithoutEmployeeNestedInput
}


/**
 * Count Type EmployeeCountOutputType
 */

export type EmployeeCountOutputType = {
  employeecheckin: number
  employeedepartment: number
  employeeinfo: number
  employeeskill: number
}

export type EmployeeCountOutputTypeSelect<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  employeecheckin?: boolean | EmployeeCountOutputTypeCountEmployeecheckinArgs
  employeedepartment?: boolean | EmployeeCountOutputTypeCountEmployeedepartmentArgs
  employeeinfo?: boolean | EmployeeCountOutputTypeCountEmployeeinfoArgs
  employeeskill?: boolean | EmployeeCountOutputTypeCountEmployeeskillArgs
}

/**
 * EmployeeCountOutputType without action
 */
export type EmployeeCountOutputTypeDefaultArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the EmployeeCountOutputType
   */
  select?: Prisma.EmployeeCountOutputTypeSelect<ExtArgs> | null
}

/**
 * EmployeeCountOutputType without action
 */
export type EmployeeCountOutputTypeCountEmployeecheckinArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  where?: Prisma.employeecheckinWhereInput
}

/**
 * EmployeeCountOutputType without action
 */
export type EmployeeCountOutputTypeCountEmployeedepartmentArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  where?: Prisma.employeedepartmentWhereInput
}

/**
 * EmployeeCountOutputType without action
 */
export type EmployeeCountOutputTypeCountEmployeeinfoArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  where?: Prisma.employeeinfoWhereInput
}

/**
 * EmployeeCountOutputType without action
 */
export type EmployeeCountOutputTypeCountEmployeeskillArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  where?: Prisma.employeeskillWhereInput
}


export type employeeSelect<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  ID?: boolean
  Name?: boolean
  employeecheckin?: boolean | Prisma.employee$employeecheckinArgs<ExtArgs>
  employeedepartment?: boolean | Prisma.employee$employeedepartmentArgs<ExtArgs>
  employeeinfo?: boolean | Prisma.employee$employeeinfoArgs<ExtArgs>
  employeeskill?: boolean | Prisma.employee$employeeskillArgs<ExtArgs>
  _count?: boolean | Prisma.EmployeeCountOutputTypeDefaultArgs<ExtArgs>
}, ExtArgs["result"]["employee"]>



export type employeeSelectScalar = {
  ID?: boolean
  Name?: boolean
}

export type employeeOmit<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetOmit<"ID" | "Name", ExtArgs["result"]["employee"]>
export type employeeInclude<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  employeecheckin?: boolean | Prisma.employee$employeecheckinArgs<ExtArgs>
  employeedepartment?: boolean | Prisma.employee$employeedepartmentArgs<ExtArgs>
  employeeinfo?: boolean | Prisma.employee$employeeinfoArgs<ExtArgs>
  employeeskill?: boolean | Prisma.employee$employeeskillArgs<ExtArgs>
  _count?: boolean | Prisma.EmployeeCountOutputTypeDefaultArgs<ExtArgs>
}

export type $employeePayload<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  name: "employee"
  objects: {
    employeecheckin: Prisma.$employeecheckinPayload<ExtArgs>[]
    employeedepartment: Prisma.$employeedepartmentPayload<ExtArgs>[]
    employeeinfo: Prisma.$employeeinfoPayload<ExtArgs>[]
    employeeskill: Prisma.$employeeskillPayload<ExtArgs>[]
  }
  scalars: runtime.Types.Extensions.GetPayloadResult<{
    ID: number
    Name: string
  }, ExtArgs["result"]["employee"]>
  composites: {}
}

export type employeeGetPayload<S extends boolean | null | undefined | employeeDefaultArgs> = runtime.Types.Result.GetResult<Prisma.$employeePayload, S>

export type employeeCountArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> =
  Omit<employeeFindManyArgs, 'select' | 'include' | 'distinct' | 'omit'> & {
    select?: EmployeeCountAggregateInputType | true
  }

export interface employeeDelegate<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs, GlobalOmitOptions = {}> {
  [K: symbol]: { types: Prisma.TypeMap<ExtArgs>['model']['employee'], meta: { name: 'employee' } }
  /**
   * Find zero or one Employee that matches the filter.
   * @param {employeeFindUniqueArgs} args - Arguments to find a Employee
   * @example
   * // Get one Employee
   * const employee = await prisma.employee.findUnique({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findUnique<T extends employeeFindUniqueArgs>(args: Prisma.SelectSubset<T, employeeFindUniqueArgs<ExtArgs>>): Prisma.Prisma__employeeClient<runtime.Types.Result.GetResult<Prisma.$employeePayload<ExtArgs>, T, "findUnique", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>

  /**
   * Find one Employee that matches the filter or throw an error with `error.code='P2025'`
   * if no matches were found.
   * @param {employeeFindUniqueOrThrowArgs} args - Arguments to find a Employee
   * @example
   * // Get one Employee
   * const employee = await prisma.employee.findUniqueOrThrow({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findUniqueOrThrow<T extends employeeFindUniqueOrThrowArgs>(args: Prisma.SelectSubset<T, employeeFindUniqueOrThrowArgs<ExtArgs>>): Prisma.Prisma__employeeClient<runtime.Types.Result.GetResult<Prisma.$employeePayload<ExtArgs>, T, "findUniqueOrThrow", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Find the first Employee that matches the filter.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {employeeFindFirstArgs} args - Arguments to find a Employee
   * @example
   * // Get one Employee
   * const employee = await prisma.employee.findFirst({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findFirst<T extends employeeFindFirstArgs>(args?: Prisma.SelectSubset<T, employeeFindFirstArgs<ExtArgs>>): Prisma.Prisma__employeeClient<runtime.Types.Result.GetResult<Prisma.$employeePayload<ExtArgs>, T, "findFirst", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>

  /**
   * Find the first Employee that matches the filter or
   * throw `PrismaKnownClientError` with `P2025` code if no matches were found.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {employeeFindFirstOrThrowArgs} args - Arguments to find a Employee
   * @example
   * // Get one Employee
   * const employee = await prisma.employee.findFirstOrThrow({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findFirstOrThrow<T extends employeeFindFirstOrThrowArgs>(args?: Prisma.SelectSubset<T, employeeFindFirstOrThrowArgs<ExtArgs>>): Prisma.Prisma__employeeClient<runtime.Types.Result.GetResult<Prisma.$employeePayload<ExtArgs>, T, "findFirstOrThrow", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Find zero or more Employees that matches the filter.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {employeeFindManyArgs} args - Arguments to filter and select certain fields only.
   * @example
   * // Get all Employees
   * const employees = await prisma.employee.findMany()
   * 
   * // Get first 10 Employees
   * const employees = await prisma.employee.findMany({ take: 10 })
   * 
   * // Only select the `ID`
   * const employeeWithIDOnly = await prisma.employee.findMany({ select: { ID: true } })
   * 
   */
  findMany<T extends employeeFindManyArgs>(args?: Prisma.SelectSubset<T, employeeFindManyArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$employeePayload<ExtArgs>, T, "findMany", GlobalOmitOptions>>

  /**
   * Create a Employee.
   * @param {employeeCreateArgs} args - Arguments to create a Employee.
   * @example
   * // Create one Employee
   * const Employee = await prisma.employee.create({
   *   data: {
   *     // ... data to create a Employee
   *   }
   * })
   * 
   */
  create<T extends employeeCreateArgs>(args: Prisma.SelectSubset<T, employeeCreateArgs<ExtArgs>>): Prisma.Prisma__employeeClient<runtime.Types.Result.GetResult<Prisma.$employeePayload<ExtArgs>, T, "create", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Create many Employees.
   * @param {employeeCreateManyArgs} args - Arguments to create many Employees.
   * @example
   * // Create many Employees
   * const employee = await prisma.employee.createMany({
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   *     
   */
  createMany<T extends employeeCreateManyArgs>(args?: Prisma.SelectSubset<T, employeeCreateManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Delete a Employee.
   * @param {employeeDeleteArgs} args - Arguments to delete one Employee.
   * @example
   * // Delete one Employee
   * const Employee = await prisma.employee.delete({
   *   where: {
   *     // ... filter to delete one Employee
   *   }
   * })
   * 
   */
  delete<T extends employeeDeleteArgs>(args: Prisma.SelectSubset<T, employeeDeleteArgs<ExtArgs>>): Prisma.Prisma__employeeClient<runtime.Types.Result.GetResult<Prisma.$employeePayload<ExtArgs>, T, "delete", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Update one Employee.
   * @param {employeeUpdateArgs} args - Arguments to update one Employee.
   * @example
   * // Update one Employee
   * const employee = await prisma.employee.update({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: {
   *     // ... provide data here
   *   }
   * })
   * 
   */
  update<T extends employeeUpdateArgs>(args: Prisma.SelectSubset<T, employeeUpdateArgs<ExtArgs>>): Prisma.Prisma__employeeClient<runtime.Types.Result.GetResult<Prisma.$employeePayload<ExtArgs>, T, "update", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Delete zero or more Employees.
   * @param {employeeDeleteManyArgs} args - Arguments to filter Employees to delete.
   * @example
   * // Delete a few Employees
   * const { count } = await prisma.employee.deleteMany({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   * 
   */
  deleteMany<T extends employeeDeleteManyArgs>(args?: Prisma.SelectSubset<T, employeeDeleteManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Update zero or more Employees.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {employeeUpdateManyArgs} args - Arguments to update one or more rows.
   * @example
   * // Update many Employees
   * const employee = await prisma.employee.updateMany({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: {
   *     // ... provide data here
   *   }
   * })
   * 
   */
  updateMany<T extends employeeUpdateManyArgs>(args: Prisma.SelectSubset<T, employeeUpdateManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Create or update one Employee.
   * @param {employeeUpsertArgs} args - Arguments to update or create a Employee.
   * @example
   * // Update or create a Employee
   * const employee = await prisma.employee.upsert({
   *   create: {
   *     // ... data to create a Employee
   *   },
   *   update: {
   *     // ... in case it already exists, update
   *   },
   *   where: {
   *     // ... the filter for the Employee we want to update
   *   }
   * })
   */
  upsert<T extends employeeUpsertArgs>(args: Prisma.SelectSubset<T, employeeUpsertArgs<ExtArgs>>): Prisma.Prisma__employeeClient<runtime.Types.Result.GetResult<Prisma.$employeePayload<ExtArgs>, T, "upsert", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>


  /**
   * Count the number of Employees.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {employeeCountArgs} args - Arguments to filter Employees to count.
   * @example
   * // Count the number of Employees
   * const count = await prisma.employee.count({
   *   where: {
   *     // ... the filter for the Employees we want to count
   *   }
   * })
  **/
  count<T extends employeeCountArgs>(
    args?: Prisma.Subset<T, employeeCountArgs>,
  ): Prisma.PrismaPromise<
    T extends runtime.Types.Utils.Record<'select', any>
      ? T['select'] extends true
        ? number
        : Prisma.GetScalarType<T['select'], EmployeeCountAggregateOutputType>
      : number
  >

  /**
   * Allows you to perform aggregations operations on a Employee.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {EmployeeAggregateArgs} args - Select which aggregations you would like to apply and on what fields.
   * @example
   * // Ordered by age ascending
   * // Where email contains prisma.io
   * // Limited to the 10 users
   * const aggregations = await prisma.user.aggregate({
   *   _avg: {
   *     age: true,
   *   },
   *   where: {
   *     email: {
   *       contains: "prisma.io",
   *     },
   *   },
   *   orderBy: {
   *     age: "asc",
   *   },
   *   take: 10,
   * })
  **/
  aggregate<T extends EmployeeAggregateArgs>(args: Prisma.Subset<T, EmployeeAggregateArgs>): Prisma.PrismaPromise<GetEmployeeAggregateType<T>>

  /**
   * Group by Employee.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {employeeGroupByArgs} args - Group by arguments.
   * @example
   * // Group by city, order by createdAt, get count
   * const result = await prisma.user.groupBy({
   *   by: ['city', 'createdAt'],
   *   orderBy: {
   *     createdAt: true
   *   },
   *   _count: {
   *     _all: true
   *   },
   * })
   * 
  **/
  groupBy<
    T extends employeeGroupByArgs,
    HasSelectOrTake extends Prisma.Or<
      Prisma.Extends<'skip', Prisma.Keys<T>>,
      Prisma.Extends<'take', Prisma.Keys<T>>
    >,
    OrderByArg extends Prisma.True extends HasSelectOrTake
      ? { orderBy: employeeGroupByArgs['orderBy'] }
      : { orderBy?: employeeGroupByArgs['orderBy'] },
    OrderFields extends Prisma.ExcludeUnderscoreKeys<Prisma.Keys<Prisma.MaybeTupleToUnion<T['orderBy']>>>,
    ByFields extends Prisma.MaybeTupleToUnion<T['by']>,
    ByValid extends Prisma.Has<ByFields, OrderFields>,
    HavingFields extends Prisma.GetHavingFields<T['having']>,
    HavingValid extends Prisma.Has<ByFields, HavingFields>,
    ByEmpty extends T['by'] extends never[] ? Prisma.True : Prisma.False,
    InputErrors extends ByEmpty extends Prisma.True
    ? `Error: "by" must not be empty.`
    : HavingValid extends Prisma.False
    ? {
        [P in HavingFields]: P extends ByFields
          ? never
          : P extends string
          ? `Error: Field "${P}" used in "having" needs to be provided in "by".`
          : [
              Error,
              'Field ',
              P,
              ` in "having" needs to be provided in "by"`,
            ]
      }[HavingFields]
    : 'take' extends Prisma.Keys<T>
    ? 'orderBy' extends Prisma.Keys<T>
      ? ByValid extends Prisma.True
        ? {}
        : {
            [P in OrderFields]: P extends ByFields
              ? never
              : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
          }[OrderFields]
      : 'Error: If you provide "take", you also need to provide "orderBy"'
    : 'skip' extends Prisma.Keys<T>
    ? 'orderBy' extends Prisma.Keys<T>
      ? ByValid extends Prisma.True
        ? {}
        : {
            [P in OrderFields]: P extends ByFields
              ? never
              : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
          }[OrderFields]
      : 'Error: If you provide "skip", you also need to provide "orderBy"'
    : ByValid extends Prisma.True
    ? {}
    : {
        [P in OrderFields]: P extends ByFields
          ? never
          : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
      }[OrderFields]
  >(args: Prisma.SubsetIntersection<T, employeeGroupByArgs, OrderByArg> & InputErrors): {} extends InputErrors ? GetEmployeeGroupByPayload<T> : Prisma.PrismaPromise<InputErrors>
/**
 * Fields of the employee model
 */
readonly fields: employeeFieldRefs;
}

/**
 * The delegate class that acts as a "Promise-like" for employee.
 * Why is this prefixed with `Prisma__`?
 * Because we want to prevent naming conflicts as mentioned in
 * https://github.com/prisma/prisma-client-js/issues/707
 */
export interface Prisma__employeeClient<T, Null = never, ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs, GlobalOmitOptions = {}> extends Prisma.PrismaPromise<T> {
  readonly [Symbol.toStringTag]: "PrismaPromise"
  employeecheckin<T extends Prisma.employee$employeecheckinArgs<ExtArgs> = {}>(args?: Prisma.Subset<T, Prisma.employee$employeecheckinArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$employeecheckinPayload<ExtArgs>, T, "findMany", GlobalOmitOptions> | Null>
  employeedepartment<T extends Prisma.employee$employeedepartmentArgs<ExtArgs> = {}>(args?: Prisma.Subset<T, Prisma.employee$employeedepartmentArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$employeedepartmentPayload<ExtArgs>, T, "findMany", GlobalOmitOptions> | Null>
  employeeinfo<T extends Prisma.employee$employeeinfoArgs<ExtArgs> = {}>(args?: Prisma.Subset<T, Prisma.employee$employeeinfoArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$employeeinfoPayload<ExtArgs>, T, "findMany", GlobalOmitOptions> | Null>
  employeeskill<T extends Prisma.employee$employeeskillArgs<ExtArgs> = {}>(args?: Prisma.Subset<T, Prisma.employee$employeeskillArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$employeeskillPayload<ExtArgs>, T, "findMany", GlobalOmitOptions> | Null>
  /**
   * Attaches callbacks for the resolution and/or rejection of the Promise.
   * @param onfulfilled The callback to execute when the Promise is resolved.
   * @param onrejected The callback to execute when the Promise is rejected.
   * @returns A Promise for the completion of which ever callback is executed.
   */
  then<TResult1 = T, TResult2 = never>(onfulfilled?: ((value: T) => TResult1 | PromiseLike<TResult1>) | undefined | null, onrejected?: ((reason: any) => TResult2 | PromiseLike<TResult2>) | undefined | null): runtime.Types.Utils.JsPromise<TResult1 | TResult2>
  /**
   * Attaches a callback for only the rejection of the Promise.
   * @param onrejected The callback to execute when the Promise is rejected.
   * @returns A Promise for the completion of the callback.
   */
  catch<TResult = never>(onrejected?: ((reason: any) => TResult | PromiseLike<TResult>) | undefined | null): runtime.Types.Utils.JsPromise<T | TResult>
  /**
   * Attaches a callback that is invoked when the Promise is settled (fulfilled or rejected). The
   * resolved value cannot be modified from the callback.
   * @param onfinally The callback to execute when the Promise is settled (fulfilled or rejected).
   * @returns A Promise for the completion of the callback.
   */
  finally(onfinally?: (() => void) | undefined | null): runtime.Types.Utils.JsPromise<T>
}




/**
 * Fields of the employee model
 */
export interface employeeFieldRefs {
  readonly ID: Prisma.FieldRef<"employee", 'Int'>
  readonly Name: Prisma.FieldRef<"employee", 'String'>
}
    

// Custom InputTypes
/**
 * employee findUnique
 */
export type employeeFindUniqueArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the employee
   */
  select?: Prisma.employeeSelect<ExtArgs> | null
  /**
   * Omit specific fields from the employee
   */
  omit?: Prisma.employeeOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.employeeInclude<ExtArgs> | null
  /**
   * Filter, which employee to fetch.
   */
  where: Prisma.employeeWhereUniqueInput
}

/**
 * employee findUniqueOrThrow
 */
export type employeeFindUniqueOrThrowArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the employee
   */
  select?: Prisma.employeeSelect<ExtArgs> | null
  /**
   * Omit specific fields from the employee
   */
  omit?: Prisma.employeeOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.employeeInclude<ExtArgs> | null
  /**
   * Filter, which employee to fetch.
   */
  where: Prisma.employeeWhereUniqueInput
}

/**
 * employee findFirst
 */
export type employeeFindFirstArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the employee
   */
  select?: Prisma.employeeSelect<ExtArgs> | null
  /**
   * Omit specific fields from the employee
   */
  omit?: Prisma.employeeOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.employeeInclude<ExtArgs> | null
  /**
   * Filter, which employee to fetch.
   */
  where?: Prisma.employeeWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of employees to fetch.
   */
  orderBy?: Prisma.employeeOrderByWithRelationInput | Prisma.employeeOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for searching for employees.
   */
  cursor?: Prisma.employeeWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` employees from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` employees.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of employees.
   */
  distinct?: Prisma.EmployeeScalarFieldEnum | Prisma.EmployeeScalarFieldEnum[]
}

/**
 * employee findFirstOrThrow
 */
export type employeeFindFirstOrThrowArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the employee
   */
  select?: Prisma.employeeSelect<ExtArgs> | null
  /**
   * Omit specific fields from the employee
   */
  omit?: Prisma.employeeOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.employeeInclude<ExtArgs> | null
  /**
   * Filter, which employee to fetch.
   */
  where?: Prisma.employeeWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of employees to fetch.
   */
  orderBy?: Prisma.employeeOrderByWithRelationInput | Prisma.employeeOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for searching for employees.
   */
  cursor?: Prisma.employeeWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` employees from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` employees.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of employees.
   */
  distinct?: Prisma.EmployeeScalarFieldEnum | Prisma.EmployeeScalarFieldEnum[]
}

/**
 * employee findMany
 */
export type employeeFindManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the employee
   */
  select?: Prisma.employeeSelect<ExtArgs> | null
  /**
   * Omit specific fields from the employee
   */
  omit?: Prisma.employeeOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.employeeInclude<ExtArgs> | null
  /**
   * Filter, which employees to fetch.
   */
  where?: Prisma.employeeWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of employees to fetch.
   */
  orderBy?: Prisma.employeeOrderByWithRelationInput | Prisma.employeeOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for listing employees.
   */
  cursor?: Prisma.employeeWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` employees from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` employees.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of employees.
   */
  distinct?: Prisma.EmployeeScalarFieldEnum | Prisma.EmployeeScalarFieldEnum[]
}

/**
 * employee create
 */
export type employeeCreateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the employee
   */
  select?: Prisma.employeeSelect<ExtArgs> | null
  /**
   * Omit specific fields from the employee
   */
  omit?: Prisma.employeeOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.employeeInclude<ExtArgs> | null
  /**
   * The data needed to create a employee.
   */
  data: Prisma.XOR<Prisma.employeeCreateInput, Prisma.employeeUncheckedCreateInput>
}

/**
 * employee createMany
 */
export type employeeCreateManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * The data used to create many employees.
   */
  data: Prisma.employeeCreateManyInput | Prisma.employeeCreateManyInput[]
  skipDuplicates?: boolean
}

/**
 * employee update
 */
export type employeeUpdateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the employee
   */
  select?: Prisma.employeeSelect<ExtArgs> | null
  /**
   * Omit specific fields from the employee
   */
  omit?: Prisma.employeeOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.employeeInclude<ExtArgs> | null
  /**
   * The data needed to update a employee.
   */
  data: Prisma.XOR<Prisma.employeeUpdateInput, Prisma.employeeUncheckedUpdateInput>
  /**
   * Choose, which employee to update.
   */
  where: Prisma.employeeWhereUniqueInput
}

/**
 * employee updateMany
 */
export type employeeUpdateManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * The data used to update employees.
   */
  data: Prisma.XOR<Prisma.employeeUpdateManyMutationInput, Prisma.employeeUncheckedUpdateManyInput>
  /**
   * Filter which employees to update
   */
  where?: Prisma.employeeWhereInput
  /**
   * Limit how many employees to update.
   */
  limit?: number
}

/**
 * employee upsert
 */
export type employeeUpsertArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the employee
   */
  select?: Prisma.employeeSelect<ExtArgs> | null
  /**
   * Omit specific fields from the employee
   */
  omit?: Prisma.employeeOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.employeeInclude<ExtArgs> | null
  /**
   * The filter to search for the employee to update in case it exists.
   */
  where: Prisma.employeeWhereUniqueInput
  /**
   * In case the employee found by the `where` argument doesn't exist, create a new employee with this data.
   */
  create: Prisma.XOR<Prisma.employeeCreateInput, Prisma.employeeUncheckedCreateInput>
  /**
   * In case the employee was found with the provided `where` argument, update it with this data.
   */
  update: Prisma.XOR<Prisma.employeeUpdateInput, Prisma.employeeUncheckedUpdateInput>
}

/**
 * employee delete
 */
export type employeeDeleteArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the employee
   */
  select?: Prisma.employeeSelect<ExtArgs> | null
  /**
   * Omit specific fields from the employee
   */
  omit?: Prisma.employeeOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.employeeInclude<ExtArgs> | null
  /**
   * Filter which employee to delete.
   */
  where: Prisma.employeeWhereUniqueInput
}

/**
 * employee deleteMany
 */
export type employeeDeleteManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Filter which employees to delete
   */
  where?: Prisma.employeeWhereInput
  /**
   * Limit how many employees to delete.
   */
  limit?: number
}

/**
 * employee.employeecheckin
 */
export type employee$employeecheckinArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the employeecheckin
   */
  select?: Prisma.employeecheckinSelect<ExtArgs> | null
  /**
   * Omit specific fields from the employeecheckin
   */
  omit?: Prisma.employeecheckinOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.employeecheckinInclude<ExtArgs> | null
  where?: Prisma.employeecheckinWhereInput
  orderBy?: Prisma.employeecheckinOrderByWithRelationInput | Prisma.employeecheckinOrderByWithRelationInput[]
  cursor?: Prisma.employeecheckinWhereUniqueInput
  take?: number
  skip?: number
  distinct?: Prisma.EmployeecheckinScalarFieldEnum | Prisma.EmployeecheckinScalarFieldEnum[]
}

/**
 * employee.employeedepartment
 */
export type employee$employeedepartmentArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the employeedepartment
   */
  select?: Prisma.employeedepartmentSelect<ExtArgs> | null
  /**
   * Omit specific fields from the employeedepartment
   */
  omit?: Prisma.employeedepartmentOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.employeedepartmentInclude<ExtArgs> | null
  where?: Prisma.employeedepartmentWhereInput
  orderBy?: Prisma.employeedepartmentOrderByWithRelationInput | Prisma.employeedepartmentOrderByWithRelationInput[]
  cursor?: Prisma.employeedepartmentWhereUniqueInput
  take?: number
  skip?: number
  distinct?: Prisma.EmployeedepartmentScalarFieldEnum | Prisma.EmployeedepartmentScalarFieldEnum[]
}

/**
 * employee.employeeinfo
 */
export type employee$employeeinfoArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the employeeinfo
   */
  select?: Prisma.employeeinfoSelect<ExtArgs> | null
  /**
   * Omit specific fields from the employeeinfo
   */
  omit?: Prisma.employeeinfoOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.employeeinfoInclude<ExtArgs> | null
  where?: Prisma.employeeinfoWhereInput
  orderBy?: Prisma.employeeinfoOrderByWithRelationInput | Prisma.employeeinfoOrderByWithRelationInput[]
  cursor?: Prisma.employeeinfoWhereUniqueInput
  take?: number
  skip?: number
  distinct?: Prisma.EmployeeinfoScalarFieldEnum | Prisma.EmployeeinfoScalarFieldEnum[]
}

/**
 * employee.employeeskill
 */
export type employee$employeeskillArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the employeeskill
   */
  select?: Prisma.employeeskillSelect<ExtArgs> | null
  /**
   * Omit specific fields from the employeeskill
   */
  omit?: Prisma.employeeskillOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.employeeskillInclude<ExtArgs> | null
  where?: Prisma.employeeskillWhereInput
  orderBy?: Prisma.employeeskillOrderByWithRelationInput | Prisma.employeeskillOrderByWithRelationInput[]
  cursor?: Prisma.employeeskillWhereUniqueInput
  take?: number
  skip?: number
  distinct?: Prisma.EmployeeskillScalarFieldEnum | Prisma.EmployeeskillScalarFieldEnum[]
}

/**
 * employee without action
 */
export type employeeDefaultArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the employee
   */
  select?: Prisma.employeeSelect<ExtArgs> | null
  /**
   * Omit specific fields from the employee
   */
  omit?: Prisma.employeeOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.employeeInclude<ExtArgs> | null
}
