
/* !!! This is code generated by Prisma. Do not edit directly. !!! */
/* eslint-disable */
// biome-ignore-all lint: generated file
// @ts-nocheck 
/*
 * This file exports the `employeeskill` model and its related types.
 *
 * 🟢 You can import this file directly.
 */
import type * as runtime from "@prisma/client/runtime/client"
import type * as $Enums from "../enums.ts"
import type * as Prisma from "../internal/prismaNamespace.ts"

/**
 * Model employeeskill
 * 
 */
export type employeeskillModel = runtime.Types.Result.DefaultSelection<Prisma.$employeeskillPayload>

export type AggregateEmployeeskill = {
  _count: EmployeeskillCountAggregateOutputType | null
  _avg: EmployeeskillAvgAggregateOutputType | null
  _sum: EmployeeskillSumAggregateOutputType | null
  _min: EmployeeskillMinAggregateOutputType | null
  _max: EmployeeskillMaxAggregateOutputType | null
}

export type EmployeeskillAvgAggregateOutputType = {
  EmployeeId: number | null
  SkillId: number | null
}

export type EmployeeskillSumAggregateOutputType = {
  EmployeeId: number | null
  SkillId: number | null
}

export type EmployeeskillMinAggregateOutputType = {
  EmployeeId: number | null
  SkillId: number | null
}

export type EmployeeskillMaxAggregateOutputType = {
  EmployeeId: number | null
  SkillId: number | null
}

export type EmployeeskillCountAggregateOutputType = {
  EmployeeId: number
  SkillId: number
  _all: number
}


export type EmployeeskillAvgAggregateInputType = {
  EmployeeId?: true
  SkillId?: true
}

export type EmployeeskillSumAggregateInputType = {
  EmployeeId?: true
  SkillId?: true
}

export type EmployeeskillMinAggregateInputType = {
  EmployeeId?: true
  SkillId?: true
}

export type EmployeeskillMaxAggregateInputType = {
  EmployeeId?: true
  SkillId?: true
}

export type EmployeeskillCountAggregateInputType = {
  EmployeeId?: true
  SkillId?: true
  _all?: true
}

export type EmployeeskillAggregateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Filter which employeeskill to aggregate.
   */
  where?: Prisma.employeeskillWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of employeeskills to fetch.
   */
  orderBy?: Prisma.employeeskillOrderByWithRelationInput | Prisma.employeeskillOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the start position
   */
  cursor?: Prisma.employeeskillWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` employeeskills from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` employeeskills.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Count returned employeeskills
  **/
  _count?: true | EmployeeskillCountAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to average
  **/
  _avg?: EmployeeskillAvgAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to sum
  **/
  _sum?: EmployeeskillSumAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to find the minimum value
  **/
  _min?: EmployeeskillMinAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to find the maximum value
  **/
  _max?: EmployeeskillMaxAggregateInputType
}

export type GetEmployeeskillAggregateType<T extends EmployeeskillAggregateArgs> = {
      [P in keyof T & keyof AggregateEmployeeskill]: P extends '_count' | 'count'
    ? T[P] extends true
      ? number
      : Prisma.GetScalarType<T[P], AggregateEmployeeskill[P]>
    : Prisma.GetScalarType<T[P], AggregateEmployeeskill[P]>
}




export type employeeskillGroupByArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  where?: Prisma.employeeskillWhereInput
  orderBy?: Prisma.employeeskillOrderByWithAggregationInput | Prisma.employeeskillOrderByWithAggregationInput[]
  by: Prisma.EmployeeskillScalarFieldEnum[] | Prisma.EmployeeskillScalarFieldEnum
  having?: Prisma.employeeskillScalarWhereWithAggregatesInput
  take?: number
  skip?: number
  _count?: EmployeeskillCountAggregateInputType | true
  _avg?: EmployeeskillAvgAggregateInputType
  _sum?: EmployeeskillSumAggregateInputType
  _min?: EmployeeskillMinAggregateInputType
  _max?: EmployeeskillMaxAggregateInputType
}

export type EmployeeskillGroupByOutputType = {
  EmployeeId: number
  SkillId: number
  _count: EmployeeskillCountAggregateOutputType | null
  _avg: EmployeeskillAvgAggregateOutputType | null
  _sum: EmployeeskillSumAggregateOutputType | null
  _min: EmployeeskillMinAggregateOutputType | null
  _max: EmployeeskillMaxAggregateOutputType | null
}

export type GetEmployeeskillGroupByPayload<T extends employeeskillGroupByArgs> = Prisma.PrismaPromise<
  Array<
    Prisma.PickEnumerable<EmployeeskillGroupByOutputType, T['by']> &
      {
        [P in ((keyof T) & (keyof EmployeeskillGroupByOutputType))]: P extends '_count'
          ? T[P] extends boolean
            ? number
            : Prisma.GetScalarType<T[P], EmployeeskillGroupByOutputType[P]>
          : Prisma.GetScalarType<T[P], EmployeeskillGroupByOutputType[P]>
      }
    >
  >



export type employeeskillWhereInput = {
  AND?: Prisma.employeeskillWhereInput | Prisma.employeeskillWhereInput[]
  OR?: Prisma.employeeskillWhereInput[]
  NOT?: Prisma.employeeskillWhereInput | Prisma.employeeskillWhereInput[]
  EmployeeId?: Prisma.IntFilter<"employeeskill"> | number
  SkillId?: Prisma.IntFilter<"employeeskill"> | number
  employee?: Prisma.XOR<Prisma.EmployeeScalarRelationFilter, Prisma.employeeWhereInput>
  skill?: Prisma.XOR<Prisma.SkillScalarRelationFilter, Prisma.skillWhereInput>
}

export type employeeskillOrderByWithRelationInput = {
  EmployeeId?: Prisma.SortOrder
  SkillId?: Prisma.SortOrder
  employee?: Prisma.employeeOrderByWithRelationInput
  skill?: Prisma.skillOrderByWithRelationInput
}

export type employeeskillWhereUniqueInput = Prisma.AtLeast<{
  EmployeeId_SkillId?: Prisma.employeeskillEmployeeIdSkillIdCompoundUniqueInput
  AND?: Prisma.employeeskillWhereInput | Prisma.employeeskillWhereInput[]
  OR?: Prisma.employeeskillWhereInput[]
  NOT?: Prisma.employeeskillWhereInput | Prisma.employeeskillWhereInput[]
  EmployeeId?: Prisma.IntFilter<"employeeskill"> | number
  SkillId?: Prisma.IntFilter<"employeeskill"> | number
  employee?: Prisma.XOR<Prisma.EmployeeScalarRelationFilter, Prisma.employeeWhereInput>
  skill?: Prisma.XOR<Prisma.SkillScalarRelationFilter, Prisma.skillWhereInput>
}, "EmployeeId_SkillId">

export type employeeskillOrderByWithAggregationInput = {
  EmployeeId?: Prisma.SortOrder
  SkillId?: Prisma.SortOrder
  _count?: Prisma.employeeskillCountOrderByAggregateInput
  _avg?: Prisma.employeeskillAvgOrderByAggregateInput
  _max?: Prisma.employeeskillMaxOrderByAggregateInput
  _min?: Prisma.employeeskillMinOrderByAggregateInput
  _sum?: Prisma.employeeskillSumOrderByAggregateInput
}

export type employeeskillScalarWhereWithAggregatesInput = {
  AND?: Prisma.employeeskillScalarWhereWithAggregatesInput | Prisma.employeeskillScalarWhereWithAggregatesInput[]
  OR?: Prisma.employeeskillScalarWhereWithAggregatesInput[]
  NOT?: Prisma.employeeskillScalarWhereWithAggregatesInput | Prisma.employeeskillScalarWhereWithAggregatesInput[]
  EmployeeId?: Prisma.IntWithAggregatesFilter<"employeeskill"> | number
  SkillId?: Prisma.IntWithAggregatesFilter<"employeeskill"> | number
}

export type employeeskillCreateInput = {
  employee: Prisma.employeeCreateNestedOneWithoutEmployeeskillInput
  skill: Prisma.skillCreateNestedOneWithoutEmployeeskillInput
}

export type employeeskillUncheckedCreateInput = {
  EmployeeId: number
  SkillId: number
}

export type employeeskillUpdateInput = {
  employee?: Prisma.employeeUpdateOneRequiredWithoutEmployeeskillNestedInput
  skill?: Prisma.skillUpdateOneRequiredWithoutEmployeeskillNestedInput
}

export type employeeskillUncheckedUpdateInput = {
  EmployeeId?: Prisma.IntFieldUpdateOperationsInput | number
  SkillId?: Prisma.IntFieldUpdateOperationsInput | number
}

export type employeeskillCreateManyInput = {
  EmployeeId: number
  SkillId: number
}

export type employeeskillUpdateManyMutationInput = {

}

export type employeeskillUncheckedUpdateManyInput = {
  EmployeeId?: Prisma.IntFieldUpdateOperationsInput | number
  SkillId?: Prisma.IntFieldUpdateOperationsInput | number
}

export type EmployeeskillListRelationFilter = {
  every?: Prisma.employeeskillWhereInput
  some?: Prisma.employeeskillWhereInput
  none?: Prisma.employeeskillWhereInput
}

export type employeeskillOrderByRelationAggregateInput = {
  _count?: Prisma.SortOrder
}

export type employeeskillEmployeeIdSkillIdCompoundUniqueInput = {
  EmployeeId: number
  SkillId: number
}

export type employeeskillCountOrderByAggregateInput = {
  EmployeeId?: Prisma.SortOrder
  SkillId?: Prisma.SortOrder
}

export type employeeskillAvgOrderByAggregateInput = {
  EmployeeId?: Prisma.SortOrder
  SkillId?: Prisma.SortOrder
}

export type employeeskillMaxOrderByAggregateInput = {
  EmployeeId?: Prisma.SortOrder
  SkillId?: Prisma.SortOrder
}

export type employeeskillMinOrderByAggregateInput = {
  EmployeeId?: Prisma.SortOrder
  SkillId?: Prisma.SortOrder
}

export type employeeskillSumOrderByAggregateInput = {
  EmployeeId?: Prisma.SortOrder
  SkillId?: Prisma.SortOrder
}

export type employeeskillCreateNestedManyWithoutEmployeeInput = {
  create?: Prisma.XOR<Prisma.employeeskillCreateWithoutEmployeeInput, Prisma.employeeskillUncheckedCreateWithoutEmployeeInput> | Prisma.employeeskillCreateWithoutEmployeeInput[] | Prisma.employeeskillUncheckedCreateWithoutEmployeeInput[]
  connectOrCreate?: Prisma.employeeskillCreateOrConnectWithoutEmployeeInput | Prisma.employeeskillCreateOrConnectWithoutEmployeeInput[]
  createMany?: Prisma.employeeskillCreateManyEmployeeInputEnvelope
  connect?: Prisma.employeeskillWhereUniqueInput | Prisma.employeeskillWhereUniqueInput[]
}

export type employeeskillUncheckedCreateNestedManyWithoutEmployeeInput = {
  create?: Prisma.XOR<Prisma.employeeskillCreateWithoutEmployeeInput, Prisma.employeeskillUncheckedCreateWithoutEmployeeInput> | Prisma.employeeskillCreateWithoutEmployeeInput[] | Prisma.employeeskillUncheckedCreateWithoutEmployeeInput[]
  connectOrCreate?: Prisma.employeeskillCreateOrConnectWithoutEmployeeInput | Prisma.employeeskillCreateOrConnectWithoutEmployeeInput[]
  createMany?: Prisma.employeeskillCreateManyEmployeeInputEnvelope
  connect?: Prisma.employeeskillWhereUniqueInput | Prisma.employeeskillWhereUniqueInput[]
}

export type employeeskillUpdateManyWithoutEmployeeNestedInput = {
  create?: Prisma.XOR<Prisma.employeeskillCreateWithoutEmployeeInput, Prisma.employeeskillUncheckedCreateWithoutEmployeeInput> | Prisma.employeeskillCreateWithoutEmployeeInput[] | Prisma.employeeskillUncheckedCreateWithoutEmployeeInput[]
  connectOrCreate?: Prisma.employeeskillCreateOrConnectWithoutEmployeeInput | Prisma.employeeskillCreateOrConnectWithoutEmployeeInput[]
  upsert?: Prisma.employeeskillUpsertWithWhereUniqueWithoutEmployeeInput | Prisma.employeeskillUpsertWithWhereUniqueWithoutEmployeeInput[]
  createMany?: Prisma.employeeskillCreateManyEmployeeInputEnvelope
  set?: Prisma.employeeskillWhereUniqueInput | Prisma.employeeskillWhereUniqueInput[]
  disconnect?: Prisma.employeeskillWhereUniqueInput | Prisma.employeeskillWhereUniqueInput[]
  delete?: Prisma.employeeskillWhereUniqueInput | Prisma.employeeskillWhereUniqueInput[]
  connect?: Prisma.employeeskillWhereUniqueInput | Prisma.employeeskillWhereUniqueInput[]
  update?: Prisma.employeeskillUpdateWithWhereUniqueWithoutEmployeeInput | Prisma.employeeskillUpdateWithWhereUniqueWithoutEmployeeInput[]
  updateMany?: Prisma.employeeskillUpdateManyWithWhereWithoutEmployeeInput | Prisma.employeeskillUpdateManyWithWhereWithoutEmployeeInput[]
  deleteMany?: Prisma.employeeskillScalarWhereInput | Prisma.employeeskillScalarWhereInput[]
}

export type employeeskillUncheckedUpdateManyWithoutEmployeeNestedInput = {
  create?: Prisma.XOR<Prisma.employeeskillCreateWithoutEmployeeInput, Prisma.employeeskillUncheckedCreateWithoutEmployeeInput> | Prisma.employeeskillCreateWithoutEmployeeInput[] | Prisma.employeeskillUncheckedCreateWithoutEmployeeInput[]
  connectOrCreate?: Prisma.employeeskillCreateOrConnectWithoutEmployeeInput | Prisma.employeeskillCreateOrConnectWithoutEmployeeInput[]
  upsert?: Prisma.employeeskillUpsertWithWhereUniqueWithoutEmployeeInput | Prisma.employeeskillUpsertWithWhereUniqueWithoutEmployeeInput[]
  createMany?: Prisma.employeeskillCreateManyEmployeeInputEnvelope
  set?: Prisma.employeeskillWhereUniqueInput | Prisma.employeeskillWhereUniqueInput[]
  disconnect?: Prisma.employeeskillWhereUniqueInput | Prisma.employeeskillWhereUniqueInput[]
  delete?: Prisma.employeeskillWhereUniqueInput | Prisma.employeeskillWhereUniqueInput[]
  connect?: Prisma.employeeskillWhereUniqueInput | Prisma.employeeskillWhereUniqueInput[]
  update?: Prisma.employeeskillUpdateWithWhereUniqueWithoutEmployeeInput | Prisma.employeeskillUpdateWithWhereUniqueWithoutEmployeeInput[]
  updateMany?: Prisma.employeeskillUpdateManyWithWhereWithoutEmployeeInput | Prisma.employeeskillUpdateManyWithWhereWithoutEmployeeInput[]
  deleteMany?: Prisma.employeeskillScalarWhereInput | Prisma.employeeskillScalarWhereInput[]
}

export type employeeskillCreateNestedManyWithoutSkillInput = {
  create?: Prisma.XOR<Prisma.employeeskillCreateWithoutSkillInput, Prisma.employeeskillUncheckedCreateWithoutSkillInput> | Prisma.employeeskillCreateWithoutSkillInput[] | Prisma.employeeskillUncheckedCreateWithoutSkillInput[]
  connectOrCreate?: Prisma.employeeskillCreateOrConnectWithoutSkillInput | Prisma.employeeskillCreateOrConnectWithoutSkillInput[]
  createMany?: Prisma.employeeskillCreateManySkillInputEnvelope
  connect?: Prisma.employeeskillWhereUniqueInput | Prisma.employeeskillWhereUniqueInput[]
}

export type employeeskillUncheckedCreateNestedManyWithoutSkillInput = {
  create?: Prisma.XOR<Prisma.employeeskillCreateWithoutSkillInput, Prisma.employeeskillUncheckedCreateWithoutSkillInput> | Prisma.employeeskillCreateWithoutSkillInput[] | Prisma.employeeskillUncheckedCreateWithoutSkillInput[]
  connectOrCreate?: Prisma.employeeskillCreateOrConnectWithoutSkillInput | Prisma.employeeskillCreateOrConnectWithoutSkillInput[]
  createMany?: Prisma.employeeskillCreateManySkillInputEnvelope
  connect?: Prisma.employeeskillWhereUniqueInput | Prisma.employeeskillWhereUniqueInput[]
}

export type employeeskillUpdateManyWithoutSkillNestedInput = {
  create?: Prisma.XOR<Prisma.employeeskillCreateWithoutSkillInput, Prisma.employeeskillUncheckedCreateWithoutSkillInput> | Prisma.employeeskillCreateWithoutSkillInput[] | Prisma.employeeskillUncheckedCreateWithoutSkillInput[]
  connectOrCreate?: Prisma.employeeskillCreateOrConnectWithoutSkillInput | Prisma.employeeskillCreateOrConnectWithoutSkillInput[]
  upsert?: Prisma.employeeskillUpsertWithWhereUniqueWithoutSkillInput | Prisma.employeeskillUpsertWithWhereUniqueWithoutSkillInput[]
  createMany?: Prisma.employeeskillCreateManySkillInputEnvelope
  set?: Prisma.employeeskillWhereUniqueInput | Prisma.employeeskillWhereUniqueInput[]
  disconnect?: Prisma.employeeskillWhereUniqueInput | Prisma.employeeskillWhereUniqueInput[]
  delete?: Prisma.employeeskillWhereUniqueInput | Prisma.employeeskillWhereUniqueInput[]
  connect?: Prisma.employeeskillWhereUniqueInput | Prisma.employeeskillWhereUniqueInput[]
  update?: Prisma.employeeskillUpdateWithWhereUniqueWithoutSkillInput | Prisma.employeeskillUpdateWithWhereUniqueWithoutSkillInput[]
  updateMany?: Prisma.employeeskillUpdateManyWithWhereWithoutSkillInput | Prisma.employeeskillUpdateManyWithWhereWithoutSkillInput[]
  deleteMany?: Prisma.employeeskillScalarWhereInput | Prisma.employeeskillScalarWhereInput[]
}

export type employeeskillUncheckedUpdateManyWithoutSkillNestedInput = {
  create?: Prisma.XOR<Prisma.employeeskillCreateWithoutSkillInput, Prisma.employeeskillUncheckedCreateWithoutSkillInput> | Prisma.employeeskillCreateWithoutSkillInput[] | Prisma.employeeskillUncheckedCreateWithoutSkillInput[]
  connectOrCreate?: Prisma.employeeskillCreateOrConnectWithoutSkillInput | Prisma.employeeskillCreateOrConnectWithoutSkillInput[]
  upsert?: Prisma.employeeskillUpsertWithWhereUniqueWithoutSkillInput | Prisma.employeeskillUpsertWithWhereUniqueWithoutSkillInput[]
  createMany?: Prisma.employeeskillCreateManySkillInputEnvelope
  set?: Prisma.employeeskillWhereUniqueInput | Prisma.employeeskillWhereUniqueInput[]
  disconnect?: Prisma.employeeskillWhereUniqueInput | Prisma.employeeskillWhereUniqueInput[]
  delete?: Prisma.employeeskillWhereUniqueInput | Prisma.employeeskillWhereUniqueInput[]
  connect?: Prisma.employeeskillWhereUniqueInput | Prisma.employeeskillWhereUniqueInput[]
  update?: Prisma.employeeskillUpdateWithWhereUniqueWithoutSkillInput | Prisma.employeeskillUpdateWithWhereUniqueWithoutSkillInput[]
  updateMany?: Prisma.employeeskillUpdateManyWithWhereWithoutSkillInput | Prisma.employeeskillUpdateManyWithWhereWithoutSkillInput[]
  deleteMany?: Prisma.employeeskillScalarWhereInput | Prisma.employeeskillScalarWhereInput[]
}

export type employeeskillCreateWithoutEmployeeInput = {
  skill: Prisma.skillCreateNestedOneWithoutEmployeeskillInput
}

export type employeeskillUncheckedCreateWithoutEmployeeInput = {
  SkillId: number
}

export type employeeskillCreateOrConnectWithoutEmployeeInput = {
  where: Prisma.employeeskillWhereUniqueInput
  create: Prisma.XOR<Prisma.employeeskillCreateWithoutEmployeeInput, Prisma.employeeskillUncheckedCreateWithoutEmployeeInput>
}

export type employeeskillCreateManyEmployeeInputEnvelope = {
  data: Prisma.employeeskillCreateManyEmployeeInput | Prisma.employeeskillCreateManyEmployeeInput[]
  skipDuplicates?: boolean
}

export type employeeskillUpsertWithWhereUniqueWithoutEmployeeInput = {
  where: Prisma.employeeskillWhereUniqueInput
  update: Prisma.XOR<Prisma.employeeskillUpdateWithoutEmployeeInput, Prisma.employeeskillUncheckedUpdateWithoutEmployeeInput>
  create: Prisma.XOR<Prisma.employeeskillCreateWithoutEmployeeInput, Prisma.employeeskillUncheckedCreateWithoutEmployeeInput>
}

export type employeeskillUpdateWithWhereUniqueWithoutEmployeeInput = {
  where: Prisma.employeeskillWhereUniqueInput
  data: Prisma.XOR<Prisma.employeeskillUpdateWithoutEmployeeInput, Prisma.employeeskillUncheckedUpdateWithoutEmployeeInput>
}

export type employeeskillUpdateManyWithWhereWithoutEmployeeInput = {
  where: Prisma.employeeskillScalarWhereInput
  data: Prisma.XOR<Prisma.employeeskillUpdateManyMutationInput, Prisma.employeeskillUncheckedUpdateManyWithoutEmployeeInput>
}

export type employeeskillScalarWhereInput = {
  AND?: Prisma.employeeskillScalarWhereInput | Prisma.employeeskillScalarWhereInput[]
  OR?: Prisma.employeeskillScalarWhereInput[]
  NOT?: Prisma.employeeskillScalarWhereInput | Prisma.employeeskillScalarWhereInput[]
  EmployeeId?: Prisma.IntFilter<"employeeskill"> | number
  SkillId?: Prisma.IntFilter<"employeeskill"> | number
}

export type employeeskillCreateWithoutSkillInput = {
  employee: Prisma.employeeCreateNestedOneWithoutEmployeeskillInput
}

export type employeeskillUncheckedCreateWithoutSkillInput = {
  EmployeeId: number
}

export type employeeskillCreateOrConnectWithoutSkillInput = {
  where: Prisma.employeeskillWhereUniqueInput
  create: Prisma.XOR<Prisma.employeeskillCreateWithoutSkillInput, Prisma.employeeskillUncheckedCreateWithoutSkillInput>
}

export type employeeskillCreateManySkillInputEnvelope = {
  data: Prisma.employeeskillCreateManySkillInput | Prisma.employeeskillCreateManySkillInput[]
  skipDuplicates?: boolean
}

export type employeeskillUpsertWithWhereUniqueWithoutSkillInput = {
  where: Prisma.employeeskillWhereUniqueInput
  update: Prisma.XOR<Prisma.employeeskillUpdateWithoutSkillInput, Prisma.employeeskillUncheckedUpdateWithoutSkillInput>
  create: Prisma.XOR<Prisma.employeeskillCreateWithoutSkillInput, Prisma.employeeskillUncheckedCreateWithoutSkillInput>
}

export type employeeskillUpdateWithWhereUniqueWithoutSkillInput = {
  where: Prisma.employeeskillWhereUniqueInput
  data: Prisma.XOR<Prisma.employeeskillUpdateWithoutSkillInput, Prisma.employeeskillUncheckedUpdateWithoutSkillInput>
}

export type employeeskillUpdateManyWithWhereWithoutSkillInput = {
  where: Prisma.employeeskillScalarWhereInput
  data: Prisma.XOR<Prisma.employeeskillUpdateManyMutationInput, Prisma.employeeskillUncheckedUpdateManyWithoutSkillInput>
}

export type employeeskillCreateManyEmployeeInput = {
  SkillId: number
}

export type employeeskillUpdateWithoutEmployeeInput = {
  skill?: Prisma.skillUpdateOneRequiredWithoutEmployeeskillNestedInput
}

export type employeeskillUncheckedUpdateWithoutEmployeeInput = {
  SkillId?: Prisma.IntFieldUpdateOperationsInput | number
}

export type employeeskillUncheckedUpdateManyWithoutEmployeeInput = {
  SkillId?: Prisma.IntFieldUpdateOperationsInput | number
}

export type employeeskillCreateManySkillInput = {
  EmployeeId: number
}

export type employeeskillUpdateWithoutSkillInput = {
  employee?: Prisma.employeeUpdateOneRequiredWithoutEmployeeskillNestedInput
}

export type employeeskillUncheckedUpdateWithoutSkillInput = {
  EmployeeId?: Prisma.IntFieldUpdateOperationsInput | number
}

export type employeeskillUncheckedUpdateManyWithoutSkillInput = {
  EmployeeId?: Prisma.IntFieldUpdateOperationsInput | number
}



export type employeeskillSelect<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  EmployeeId?: boolean
  SkillId?: boolean
  employee?: boolean | Prisma.employeeDefaultArgs<ExtArgs>
  skill?: boolean | Prisma.skillDefaultArgs<ExtArgs>
}, ExtArgs["result"]["employeeskill"]>



export type employeeskillSelectScalar = {
  EmployeeId?: boolean
  SkillId?: boolean
}

export type employeeskillOmit<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetOmit<"EmployeeId" | "SkillId", ExtArgs["result"]["employeeskill"]>
export type employeeskillInclude<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  employee?: boolean | Prisma.employeeDefaultArgs<ExtArgs>
  skill?: boolean | Prisma.skillDefaultArgs<ExtArgs>
}

export type $employeeskillPayload<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  name: "employeeskill"
  objects: {
    employee: Prisma.$employeePayload<ExtArgs>
    skill: Prisma.$skillPayload<ExtArgs>
  }
  scalars: runtime.Types.Extensions.GetPayloadResult<{
    EmployeeId: number
    SkillId: number
  }, ExtArgs["result"]["employeeskill"]>
  composites: {}
}

export type employeeskillGetPayload<S extends boolean | null | undefined | employeeskillDefaultArgs> = runtime.Types.Result.GetResult<Prisma.$employeeskillPayload, S>

export type employeeskillCountArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> =
  Omit<employeeskillFindManyArgs, 'select' | 'include' | 'distinct' | 'omit'> & {
    select?: EmployeeskillCountAggregateInputType | true
  }

export interface employeeskillDelegate<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs, GlobalOmitOptions = {}> {
  [K: symbol]: { types: Prisma.TypeMap<ExtArgs>['model']['employeeskill'], meta: { name: 'employeeskill' } }
  /**
   * Find zero or one Employeeskill that matches the filter.
   * @param {employeeskillFindUniqueArgs} args - Arguments to find a Employeeskill
   * @example
   * // Get one Employeeskill
   * const employeeskill = await prisma.employeeskill.findUnique({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findUnique<T extends employeeskillFindUniqueArgs>(args: Prisma.SelectSubset<T, employeeskillFindUniqueArgs<ExtArgs>>): Prisma.Prisma__employeeskillClient<runtime.Types.Result.GetResult<Prisma.$employeeskillPayload<ExtArgs>, T, "findUnique", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>

  /**
   * Find one Employeeskill that matches the filter or throw an error with `error.code='P2025'`
   * if no matches were found.
   * @param {employeeskillFindUniqueOrThrowArgs} args - Arguments to find a Employeeskill
   * @example
   * // Get one Employeeskill
   * const employeeskill = await prisma.employeeskill.findUniqueOrThrow({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findUniqueOrThrow<T extends employeeskillFindUniqueOrThrowArgs>(args: Prisma.SelectSubset<T, employeeskillFindUniqueOrThrowArgs<ExtArgs>>): Prisma.Prisma__employeeskillClient<runtime.Types.Result.GetResult<Prisma.$employeeskillPayload<ExtArgs>, T, "findUniqueOrThrow", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Find the first Employeeskill that matches the filter.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {employeeskillFindFirstArgs} args - Arguments to find a Employeeskill
   * @example
   * // Get one Employeeskill
   * const employeeskill = await prisma.employeeskill.findFirst({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findFirst<T extends employeeskillFindFirstArgs>(args?: Prisma.SelectSubset<T, employeeskillFindFirstArgs<ExtArgs>>): Prisma.Prisma__employeeskillClient<runtime.Types.Result.GetResult<Prisma.$employeeskillPayload<ExtArgs>, T, "findFirst", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>

  /**
   * Find the first Employeeskill that matches the filter or
   * throw `PrismaKnownClientError` with `P2025` code if no matches were found.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {employeeskillFindFirstOrThrowArgs} args - Arguments to find a Employeeskill
   * @example
   * // Get one Employeeskill
   * const employeeskill = await prisma.employeeskill.findFirstOrThrow({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findFirstOrThrow<T extends employeeskillFindFirstOrThrowArgs>(args?: Prisma.SelectSubset<T, employeeskillFindFirstOrThrowArgs<ExtArgs>>): Prisma.Prisma__employeeskillClient<runtime.Types.Result.GetResult<Prisma.$employeeskillPayload<ExtArgs>, T, "findFirstOrThrow", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Find zero or more Employeeskills that matches the filter.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {employeeskillFindManyArgs} args - Arguments to filter and select certain fields only.
   * @example
   * // Get all Employeeskills
   * const employeeskills = await prisma.employeeskill.findMany()
   * 
   * // Get first 10 Employeeskills
   * const employeeskills = await prisma.employeeskill.findMany({ take: 10 })
   * 
   * // Only select the `EmployeeId`
   * const employeeskillWithEmployeeIdOnly = await prisma.employeeskill.findMany({ select: { EmployeeId: true } })
   * 
   */
  findMany<T extends employeeskillFindManyArgs>(args?: Prisma.SelectSubset<T, employeeskillFindManyArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$employeeskillPayload<ExtArgs>, T, "findMany", GlobalOmitOptions>>

  /**
   * Create a Employeeskill.
   * @param {employeeskillCreateArgs} args - Arguments to create a Employeeskill.
   * @example
   * // Create one Employeeskill
   * const Employeeskill = await prisma.employeeskill.create({
   *   data: {
   *     // ... data to create a Employeeskill
   *   }
   * })
   * 
   */
  create<T extends employeeskillCreateArgs>(args: Prisma.SelectSubset<T, employeeskillCreateArgs<ExtArgs>>): Prisma.Prisma__employeeskillClient<runtime.Types.Result.GetResult<Prisma.$employeeskillPayload<ExtArgs>, T, "create", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Create many Employeeskills.
   * @param {employeeskillCreateManyArgs} args - Arguments to create many Employeeskills.
   * @example
   * // Create many Employeeskills
   * const employeeskill = await prisma.employeeskill.createMany({
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   *     
   */
  createMany<T extends employeeskillCreateManyArgs>(args?: Prisma.SelectSubset<T, employeeskillCreateManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Delete a Employeeskill.
   * @param {employeeskillDeleteArgs} args - Arguments to delete one Employeeskill.
   * @example
   * // Delete one Employeeskill
   * const Employeeskill = await prisma.employeeskill.delete({
   *   where: {
   *     // ... filter to delete one Employeeskill
   *   }
   * })
   * 
   */
  delete<T extends employeeskillDeleteArgs>(args: Prisma.SelectSubset<T, employeeskillDeleteArgs<ExtArgs>>): Prisma.Prisma__employeeskillClient<runtime.Types.Result.GetResult<Prisma.$employeeskillPayload<ExtArgs>, T, "delete", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Update one Employeeskill.
   * @param {employeeskillUpdateArgs} args - Arguments to update one Employeeskill.
   * @example
   * // Update one Employeeskill
   * const employeeskill = await prisma.employeeskill.update({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: {
   *     // ... provide data here
   *   }
   * })
   * 
   */
  update<T extends employeeskillUpdateArgs>(args: Prisma.SelectSubset<T, employeeskillUpdateArgs<ExtArgs>>): Prisma.Prisma__employeeskillClient<runtime.Types.Result.GetResult<Prisma.$employeeskillPayload<ExtArgs>, T, "update", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Delete zero or more Employeeskills.
   * @param {employeeskillDeleteManyArgs} args - Arguments to filter Employeeskills to delete.
   * @example
   * // Delete a few Employeeskills
   * const { count } = await prisma.employeeskill.deleteMany({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   * 
   */
  deleteMany<T extends employeeskillDeleteManyArgs>(args?: Prisma.SelectSubset<T, employeeskillDeleteManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Update zero or more Employeeskills.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {employeeskillUpdateManyArgs} args - Arguments to update one or more rows.
   * @example
   * // Update many Employeeskills
   * const employeeskill = await prisma.employeeskill.updateMany({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: {
   *     // ... provide data here
   *   }
   * })
   * 
   */
  updateMany<T extends employeeskillUpdateManyArgs>(args: Prisma.SelectSubset<T, employeeskillUpdateManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Create or update one Employeeskill.
   * @param {employeeskillUpsertArgs} args - Arguments to update or create a Employeeskill.
   * @example
   * // Update or create a Employeeskill
   * const employeeskill = await prisma.employeeskill.upsert({
   *   create: {
   *     // ... data to create a Employeeskill
   *   },
   *   update: {
   *     // ... in case it already exists, update
   *   },
   *   where: {
   *     // ... the filter for the Employeeskill we want to update
   *   }
   * })
   */
  upsert<T extends employeeskillUpsertArgs>(args: Prisma.SelectSubset<T, employeeskillUpsertArgs<ExtArgs>>): Prisma.Prisma__employeeskillClient<runtime.Types.Result.GetResult<Prisma.$employeeskillPayload<ExtArgs>, T, "upsert", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>


  /**
   * Count the number of Employeeskills.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {employeeskillCountArgs} args - Arguments to filter Employeeskills to count.
   * @example
   * // Count the number of Employeeskills
   * const count = await prisma.employeeskill.count({
   *   where: {
   *     // ... the filter for the Employeeskills we want to count
   *   }
   * })
  **/
  count<T extends employeeskillCountArgs>(
    args?: Prisma.Subset<T, employeeskillCountArgs>,
  ): Prisma.PrismaPromise<
    T extends runtime.Types.Utils.Record<'select', any>
      ? T['select'] extends true
        ? number
        : Prisma.GetScalarType<T['select'], EmployeeskillCountAggregateOutputType>
      : number
  >

  /**
   * Allows you to perform aggregations operations on a Employeeskill.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {EmployeeskillAggregateArgs} args - Select which aggregations you would like to apply and on what fields.
   * @example
   * // Ordered by age ascending
   * // Where email contains prisma.io
   * // Limited to the 10 users
   * const aggregations = await prisma.user.aggregate({
   *   _avg: {
   *     age: true,
   *   },
   *   where: {
   *     email: {
   *       contains: "prisma.io",
   *     },
   *   },
   *   orderBy: {
   *     age: "asc",
   *   },
   *   take: 10,
   * })
  **/
  aggregate<T extends EmployeeskillAggregateArgs>(args: Prisma.Subset<T, EmployeeskillAggregateArgs>): Prisma.PrismaPromise<GetEmployeeskillAggregateType<T>>

  /**
   * Group by Employeeskill.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {employeeskillGroupByArgs} args - Group by arguments.
   * @example
   * // Group by city, order by createdAt, get count
   * const result = await prisma.user.groupBy({
   *   by: ['city', 'createdAt'],
   *   orderBy: {
   *     createdAt: true
   *   },
   *   _count: {
   *     _all: true
   *   },
   * })
   * 
  **/
  groupBy<
    T extends employeeskillGroupByArgs,
    HasSelectOrTake extends Prisma.Or<
      Prisma.Extends<'skip', Prisma.Keys<T>>,
      Prisma.Extends<'take', Prisma.Keys<T>>
    >,
    OrderByArg extends Prisma.True extends HasSelectOrTake
      ? { orderBy: employeeskillGroupByArgs['orderBy'] }
      : { orderBy?: employeeskillGroupByArgs['orderBy'] },
    OrderFields extends Prisma.ExcludeUnderscoreKeys<Prisma.Keys<Prisma.MaybeTupleToUnion<T['orderBy']>>>,
    ByFields extends Prisma.MaybeTupleToUnion<T['by']>,
    ByValid extends Prisma.Has<ByFields, OrderFields>,
    HavingFields extends Prisma.GetHavingFields<T['having']>,
    HavingValid extends Prisma.Has<ByFields, HavingFields>,
    ByEmpty extends T['by'] extends never[] ? Prisma.True : Prisma.False,
    InputErrors extends ByEmpty extends Prisma.True
    ? `Error: "by" must not be empty.`
    : HavingValid extends Prisma.False
    ? {
        [P in HavingFields]: P extends ByFields
          ? never
          : P extends string
          ? `Error: Field "${P}" used in "having" needs to be provided in "by".`
          : [
              Error,
              'Field ',
              P,
              ` in "having" needs to be provided in "by"`,
            ]
      }[HavingFields]
    : 'take' extends Prisma.Keys<T>
    ? 'orderBy' extends Prisma.Keys<T>
      ? ByValid extends Prisma.True
        ? {}
        : {
            [P in OrderFields]: P extends ByFields
              ? never
              : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
          }[OrderFields]
      : 'Error: If you provide "take", you also need to provide "orderBy"'
    : 'skip' extends Prisma.Keys<T>
    ? 'orderBy' extends Prisma.Keys<T>
      ? ByValid extends Prisma.True
        ? {}
        : {
            [P in OrderFields]: P extends ByFields
              ? never
              : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
          }[OrderFields]
      : 'Error: If you provide "skip", you also need to provide "orderBy"'
    : ByValid extends Prisma.True
    ? {}
    : {
        [P in OrderFields]: P extends ByFields
          ? never
          : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
      }[OrderFields]
  >(args: Prisma.SubsetIntersection<T, employeeskillGroupByArgs, OrderByArg> & InputErrors): {} extends InputErrors ? GetEmployeeskillGroupByPayload<T> : Prisma.PrismaPromise<InputErrors>
/**
 * Fields of the employeeskill model
 */
readonly fields: employeeskillFieldRefs;
}

/**
 * The delegate class that acts as a "Promise-like" for employeeskill.
 * Why is this prefixed with `Prisma__`?
 * Because we want to prevent naming conflicts as mentioned in
 * https://github.com/prisma/prisma-client-js/issues/707
 */
export interface Prisma__employeeskillClient<T, Null = never, ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs, GlobalOmitOptions = {}> extends Prisma.PrismaPromise<T> {
  readonly [Symbol.toStringTag]: "PrismaPromise"
  employee<T extends Prisma.employeeDefaultArgs<ExtArgs> = {}>(args?: Prisma.Subset<T, Prisma.employeeDefaultArgs<ExtArgs>>): Prisma.Prisma__employeeClient<runtime.Types.Result.GetResult<Prisma.$employeePayload<ExtArgs>, T, "findUniqueOrThrow", GlobalOmitOptions> | Null, Null, ExtArgs, GlobalOmitOptions>
  skill<T extends Prisma.skillDefaultArgs<ExtArgs> = {}>(args?: Prisma.Subset<T, Prisma.skillDefaultArgs<ExtArgs>>): Prisma.Prisma__skillClient<runtime.Types.Result.GetResult<Prisma.$skillPayload<ExtArgs>, T, "findUniqueOrThrow", GlobalOmitOptions> | Null, Null, ExtArgs, GlobalOmitOptions>
  /**
   * Attaches callbacks for the resolution and/or rejection of the Promise.
   * @param onfulfilled The callback to execute when the Promise is resolved.
   * @param onrejected The callback to execute when the Promise is rejected.
   * @returns A Promise for the completion of which ever callback is executed.
   */
  then<TResult1 = T, TResult2 = never>(onfulfilled?: ((value: T) => TResult1 | PromiseLike<TResult1>) | undefined | null, onrejected?: ((reason: any) => TResult2 | PromiseLike<TResult2>) | undefined | null): runtime.Types.Utils.JsPromise<TResult1 | TResult2>
  /**
   * Attaches a callback for only the rejection of the Promise.
   * @param onrejected The callback to execute when the Promise is rejected.
   * @returns A Promise for the completion of the callback.
   */
  catch<TResult = never>(onrejected?: ((reason: any) => TResult | PromiseLike<TResult>) | undefined | null): runtime.Types.Utils.JsPromise<T | TResult>
  /**
   * Attaches a callback that is invoked when the Promise is settled (fulfilled or rejected). The
   * resolved value cannot be modified from the callback.
   * @param onfinally The callback to execute when the Promise is settled (fulfilled or rejected).
   * @returns A Promise for the completion of the callback.
   */
  finally(onfinally?: (() => void) | undefined | null): runtime.Types.Utils.JsPromise<T>
}




/**
 * Fields of the employeeskill model
 */
export interface employeeskillFieldRefs {
  readonly EmployeeId: Prisma.FieldRef<"employeeskill", 'Int'>
  readonly SkillId: Prisma.FieldRef<"employeeskill", 'Int'>
}
    

// Custom InputTypes
/**
 * employeeskill findUnique
 */
export type employeeskillFindUniqueArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the employeeskill
   */
  select?: Prisma.employeeskillSelect<ExtArgs> | null
  /**
   * Omit specific fields from the employeeskill
   */
  omit?: Prisma.employeeskillOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.employeeskillInclude<ExtArgs> | null
  /**
   * Filter, which employeeskill to fetch.
   */
  where: Prisma.employeeskillWhereUniqueInput
}

/**
 * employeeskill findUniqueOrThrow
 */
export type employeeskillFindUniqueOrThrowArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the employeeskill
   */
  select?: Prisma.employeeskillSelect<ExtArgs> | null
  /**
   * Omit specific fields from the employeeskill
   */
  omit?: Prisma.employeeskillOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.employeeskillInclude<ExtArgs> | null
  /**
   * Filter, which employeeskill to fetch.
   */
  where: Prisma.employeeskillWhereUniqueInput
}

/**
 * employeeskill findFirst
 */
export type employeeskillFindFirstArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the employeeskill
   */
  select?: Prisma.employeeskillSelect<ExtArgs> | null
  /**
   * Omit specific fields from the employeeskill
   */
  omit?: Prisma.employeeskillOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.employeeskillInclude<ExtArgs> | null
  /**
   * Filter, which employeeskill to fetch.
   */
  where?: Prisma.employeeskillWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of employeeskills to fetch.
   */
  orderBy?: Prisma.employeeskillOrderByWithRelationInput | Prisma.employeeskillOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for searching for employeeskills.
   */
  cursor?: Prisma.employeeskillWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` employeeskills from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` employeeskills.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of employeeskills.
   */
  distinct?: Prisma.EmployeeskillScalarFieldEnum | Prisma.EmployeeskillScalarFieldEnum[]
}

/**
 * employeeskill findFirstOrThrow
 */
export type employeeskillFindFirstOrThrowArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the employeeskill
   */
  select?: Prisma.employeeskillSelect<ExtArgs> | null
  /**
   * Omit specific fields from the employeeskill
   */
  omit?: Prisma.employeeskillOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.employeeskillInclude<ExtArgs> | null
  /**
   * Filter, which employeeskill to fetch.
   */
  where?: Prisma.employeeskillWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of employeeskills to fetch.
   */
  orderBy?: Prisma.employeeskillOrderByWithRelationInput | Prisma.employeeskillOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for searching for employeeskills.
   */
  cursor?: Prisma.employeeskillWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` employeeskills from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` employeeskills.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of employeeskills.
   */
  distinct?: Prisma.EmployeeskillScalarFieldEnum | Prisma.EmployeeskillScalarFieldEnum[]
}

/**
 * employeeskill findMany
 */
export type employeeskillFindManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the employeeskill
   */
  select?: Prisma.employeeskillSelect<ExtArgs> | null
  /**
   * Omit specific fields from the employeeskill
   */
  omit?: Prisma.employeeskillOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.employeeskillInclude<ExtArgs> | null
  /**
   * Filter, which employeeskills to fetch.
   */
  where?: Prisma.employeeskillWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of employeeskills to fetch.
   */
  orderBy?: Prisma.employeeskillOrderByWithRelationInput | Prisma.employeeskillOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for listing employeeskills.
   */
  cursor?: Prisma.employeeskillWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` employeeskills from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` employeeskills.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of employeeskills.
   */
  distinct?: Prisma.EmployeeskillScalarFieldEnum | Prisma.EmployeeskillScalarFieldEnum[]
}

/**
 * employeeskill create
 */
export type employeeskillCreateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the employeeskill
   */
  select?: Prisma.employeeskillSelect<ExtArgs> | null
  /**
   * Omit specific fields from the employeeskill
   */
  omit?: Prisma.employeeskillOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.employeeskillInclude<ExtArgs> | null
  /**
   * The data needed to create a employeeskill.
   */
  data: Prisma.XOR<Prisma.employeeskillCreateInput, Prisma.employeeskillUncheckedCreateInput>
}

/**
 * employeeskill createMany
 */
export type employeeskillCreateManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * The data used to create many employeeskills.
   */
  data: Prisma.employeeskillCreateManyInput | Prisma.employeeskillCreateManyInput[]
  skipDuplicates?: boolean
}

/**
 * employeeskill update
 */
export type employeeskillUpdateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the employeeskill
   */
  select?: Prisma.employeeskillSelect<ExtArgs> | null
  /**
   * Omit specific fields from the employeeskill
   */
  omit?: Prisma.employeeskillOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.employeeskillInclude<ExtArgs> | null
  /**
   * The data needed to update a employeeskill.
   */
  data: Prisma.XOR<Prisma.employeeskillUpdateInput, Prisma.employeeskillUncheckedUpdateInput>
  /**
   * Choose, which employeeskill to update.
   */
  where: Prisma.employeeskillWhereUniqueInput
}

/**
 * employeeskill updateMany
 */
export type employeeskillUpdateManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * The data used to update employeeskills.
   */
  data: Prisma.XOR<Prisma.employeeskillUpdateManyMutationInput, Prisma.employeeskillUncheckedUpdateManyInput>
  /**
   * Filter which employeeskills to update
   */
  where?: Prisma.employeeskillWhereInput
  /**
   * Limit how many employeeskills to update.
   */
  limit?: number
}

/**
 * employeeskill upsert
 */
export type employeeskillUpsertArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the employeeskill
   */
  select?: Prisma.employeeskillSelect<ExtArgs> | null
  /**
   * Omit specific fields from the employeeskill
   */
  omit?: Prisma.employeeskillOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.employeeskillInclude<ExtArgs> | null
  /**
   * The filter to search for the employeeskill to update in case it exists.
   */
  where: Prisma.employeeskillWhereUniqueInput
  /**
   * In case the employeeskill found by the `where` argument doesn't exist, create a new employeeskill with this data.
   */
  create: Prisma.XOR<Prisma.employeeskillCreateInput, Prisma.employeeskillUncheckedCreateInput>
  /**
   * In case the employeeskill was found with the provided `where` argument, update it with this data.
   */
  update: Prisma.XOR<Prisma.employeeskillUpdateInput, Prisma.employeeskillUncheckedUpdateInput>
}

/**
 * employeeskill delete
 */
export type employeeskillDeleteArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the employeeskill
   */
  select?: Prisma.employeeskillSelect<ExtArgs> | null
  /**
   * Omit specific fields from the employeeskill
   */
  omit?: Prisma.employeeskillOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.employeeskillInclude<ExtArgs> | null
  /**
   * Filter which employeeskill to delete.
   */
  where: Prisma.employeeskillWhereUniqueInput
}

/**
 * employeeskill deleteMany
 */
export type employeeskillDeleteManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Filter which employeeskills to delete
   */
  where?: Prisma.employeeskillWhereInput
  /**
   * Limit how many employeeskills to delete.
   */
  limit?: number
}

/**
 * employeeskill without action
 */
export type employeeskillDefaultArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the employeeskill
   */
  select?: Prisma.employeeskillSelect<ExtArgs> | null
  /**
   * Omit specific fields from the employeeskill
   */
  omit?: Prisma.employeeskillOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.employeeskillInclude<ExtArgs> | null
}
