
/* !!! This is code generated by Prisma. Do not edit directly. !!! */
/* eslint-disable */
// biome-ignore-all lint: generated file
// @ts-nocheck 
/*
 * This is a barrel export file for all models and their related types.
 *
 * 🟢 You can import this file directly.
 */
export type * from './models/department.ts'
export type * from './models/employee.ts'
export type * from './models/employeecheckin.ts'
export type * from './models/employeedepartment.ts'
export type * from './models/employeeinfo.ts'
export type * from './models/employeeskill.ts'
export type * from './models/skill.ts'
export type * from './commonInputTypes.ts'