/* tslint:disable */
/* eslint-disable */
/**
 * OPC UA Web API
 * Provides simple HTTPS based access to an OPC UA server.
 *
 * The version of the OpenAPI document: 1.05.4
 * Contact: office@opcfoundation.org
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * [Link to specification](https://reference.opcfoundation.org/v105/Core/docs/Part14/6.2.3/#6.2.3.10.5).
 * @export
 * @interface ActionMethodDataType
 */
export interface ActionMethodDataType {
    /**
     * 
     * @type {string}
     * @memberof ActionMethodDataType
     */
    ObjectId?: string;
    /**
     * 
     * @type {string}
     * @memberof ActionMethodDataType
     */
    MethodId?: string;
}

/**
 * Check if a given object implements the ActionMethodDataType interface.
 */
export function instanceOfActionMethodDataType(value: object): value is ActionMethodDataType {
    return true;
}

export function ActionMethodDataTypeFromJSON(json: any): ActionMethodDataType {
    return ActionMethodDataTypeFromJSONTyped(json, false);
}

export function ActionMethodDataTypeFromJSONTyped(json: any, ignoreDiscriminator: boolean): ActionMethodDataType {
    if (json == null) {
        return json;
    }
    return {
        
        'ObjectId': json['ObjectId'] == null ? undefined : json['ObjectId'],
        'MethodId': json['MethodId'] == null ? undefined : json['MethodId'],
    };
}

  export function ActionMethodDataTypeToJSON(json: any): ActionMethodDataType {
      return ActionMethodDataTypeToJSONTyped(json, false);
  }

  export function ActionMethodDataTypeToJSONTyped(value?: ActionMethodDataType | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'ObjectId': value['ObjectId'],
        'MethodId': value['MethodId'],
    };
}

