/* tslint:disable */
/* eslint-disable */
/**
 * OPC UA Web API
 * Provides simple HTTPS based access to an OPC UA server.
 *
 * The version of the OpenAPI document: 1.05.4
 * Contact: office@opcfoundation.org
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { ResponseHeader } from './ResponseHeader';
import {
    ResponseHeaderFromJSON,
    ResponseHeaderFromJSONTyped,
    ResponseHeaderToJSON,
    ResponseHeaderToJSONTyped,
} from './ResponseHeader';
import type { AddNodesResult } from './AddNodesResult';
import {
    AddNodesResultFromJSON,
    AddNodesResultFromJSONTyped,
    AddNodesResultToJSON,
    AddNodesResultToJSONTyped,
} from './AddNodesResult';
import type { DiagnosticInfo } from './DiagnosticInfo';
import {
    DiagnosticInfoFromJSON,
    DiagnosticInfoFromJSONTyped,
    DiagnosticInfoToJSON,
    DiagnosticInfoToJSONTyped,
} from './DiagnosticInfo';

/**
 * [Link to specification](https://reference.opcfoundation.org/specs/OPC-10000-4/v1.05.07/5.8.2).
 * @export
 * @interface AddNodesResponse
 */
export interface AddNodesResponse {
    /**
     * 
     * @type {ResponseHeader}
     * @memberof AddNodesResponse
     */
    ResponseHeader?: ResponseHeader;
    /**
     * 
     * @type {Array<AddNodesResult>}
     * @memberof AddNodesResponse
     */
    Results?: Array<AddNodesResult>;
    /**
     * 
     * @type {Array<DiagnosticInfo>}
     * @memberof AddNodesResponse
     */
    DiagnosticInfos?: Array<DiagnosticInfo>;
}

/**
 * Check if a given object implements the AddNodesResponse interface.
 */
export function instanceOfAddNodesResponse(value: object): value is AddNodesResponse {
    return true;
}

export function AddNodesResponseFromJSON(json: any): AddNodesResponse {
    return AddNodesResponseFromJSONTyped(json, false);
}

export function AddNodesResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): AddNodesResponse {
    if (json == null) {
        return json;
    }
    return {
        
        'ResponseHeader': json['ResponseHeader'] == null ? undefined : ResponseHeaderFromJSON(json['ResponseHeader']),
        'Results': json['Results'] == null ? undefined : ((json['Results'] as Array<any>).map(AddNodesResultFromJSON)),
        'DiagnosticInfos': json['DiagnosticInfos'] == null ? undefined : ((json['DiagnosticInfos'] as Array<any>).map(DiagnosticInfoFromJSON)),
    };
}

export function AddNodesResponseToJSON(json: any): AddNodesResponse {
    return AddNodesResponseToJSONTyped(json, false);
}

export function AddNodesResponseToJSONTyped(value?: AddNodesResponse | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'ResponseHeader': ResponseHeaderToJSON(value['ResponseHeader']),
        'Results': value['Results'] == null ? undefined : ((value['Results'] as Array<any>).map(AddNodesResultToJSON)),
        'DiagnosticInfos': value['DiagnosticInfos'] == null ? undefined : ((value['DiagnosticInfos'] as Array<any>).map(DiagnosticInfoToJSON)),
    };
}

