/* tslint:disable */
/* eslint-disable */
/**
 * OPC UA Web API
 * Provides simple HTTPS based access to an OPC UA server.
 *
 * The version of the OpenAPI document: 1.05.4
 * Contact: office@opcfoundation.org
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { AddReferencesItem } from './AddReferencesItem';
import {
    AddReferencesItemFromJSON,
    AddReferencesItemFromJSONTyped,
    AddReferencesItemToJSON,
    AddReferencesItemToJSONTyped,
} from './AddReferencesItem';
import type { RequestHeader } from './RequestHeader';
import {
    RequestHeaderFromJSON,
    RequestHeaderFromJSONTyped,
    RequestHeaderToJSON,
    RequestHeaderToJSONTyped,
} from './RequestHeader';

/**
 * [Link to specification](https://reference.opcfoundation.org/specs/OPC-10000-4/v1.05.07/5.8.3).
 * @export
 * @interface AddReferencesRequest
 */
export interface AddReferencesRequest {
    /**
     * 
     * @type {RequestHeader}
     * @memberof AddReferencesRequest
     */
    RequestHeader?: RequestHeader;
    /**
     * 
     * @type {Array<AddReferencesItem>}
     * @memberof AddReferencesRequest
     */
    ReferencesToAdd?: Array<AddReferencesItem>;
}

/**
 * Check if a given object implements the AddReferencesRequest interface.
 */
export function instanceOfAddReferencesRequest(value: object): value is AddReferencesRequest {
    return true;
}

export function AddReferencesRequestFromJSON(json: any): AddReferencesRequest {
    return AddReferencesRequestFromJSONTyped(json, false);
}

export function AddReferencesRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): AddReferencesRequest {
    if (json == null) {
        return json;
    }
    return {
        
        'RequestHeader': json['RequestHeader'] == null ? undefined : RequestHeaderFromJSON(json['RequestHeader']),
        'ReferencesToAdd': json['ReferencesToAdd'] == null ? undefined : ((json['ReferencesToAdd'] as Array<any>).map(AddReferencesItemFromJSON)),
    };
}

export function AddReferencesRequestToJSON(json: any): AddReferencesRequest {
    return AddReferencesRequestToJSONTyped(json, false);
}

export function AddReferencesRequestToJSONTyped(value?: AddReferencesRequest | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'RequestHeader': RequestHeaderToJSON(value['RequestHeader']),
        'ReferencesToAdd': value['ReferencesToAdd'] == null ? undefined : ((value['ReferencesToAdd'] as Array<any>).map(AddReferencesItemToJSON)),
    };
}

