/* tslint:disable */
/* eslint-disable */
/**
 * OPC UA Web API
 * Provides simple HTTPS based access to an OPC UA server.
 *
 * The version of the OpenAPI document: 1.05.4
 * Contact: office@opcfoundation.org
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { AggregateConfiguration } from './AggregateConfiguration';
import {
    AggregateConfigurationFromJSON,
    AggregateConfigurationFromJSONTyped,
    AggregateConfigurationToJSON,
    AggregateConfigurationToJSONTyped,
} from './AggregateConfiguration';

/**
 * [Link to specification](https://reference.opcfoundation.org/v105/Core/docs/Part4/7.22.4).
 * @export
 * @interface AggregateFilterResult
 */
export interface AggregateFilterResult {
    /**
     * 
     * @type {Date}
     * @memberof AggregateFilterResult
     */
    RevisedStartTime?: Date;
    /**
     * 
     * @type {number}
     * @memberof AggregateFilterResult
     */
    RevisedProcessingInterval?: number;
    /**
     * 
     * @type {AggregateConfiguration}
     * @memberof AggregateFilterResult
     */
    RevisedAggregateConfiguration?: AggregateConfiguration;
}

/**
 * Check if a given object implements the AggregateFilterResult interface.
 */
export function instanceOfAggregateFilterResult(value: object): value is AggregateFilterResult {
    return true;
}

export function AggregateFilterResultFromJSON(json: any): AggregateFilterResult {
    return AggregateFilterResultFromJSONTyped(json, false);
}

export function AggregateFilterResultFromJSONTyped(json: any, ignoreDiscriminator: boolean): AggregateFilterResult {
    if (json == null) {
        return json;
    }
    return {
        
        'RevisedStartTime': json['RevisedStartTime'] == null ? undefined : (new Date(json['RevisedStartTime'])),
        'RevisedProcessingInterval': json['RevisedProcessingInterval'] == null ? undefined : json['RevisedProcessingInterval'],
        'RevisedAggregateConfiguration': json['RevisedAggregateConfiguration'] == null ? undefined : AggregateConfigurationFromJSON(json['RevisedAggregateConfiguration']),
    };
}

  export function AggregateFilterResultToJSON(json: any): AggregateFilterResult {
      return AggregateFilterResultToJSONTyped(json, false);
  }

  export function AggregateFilterResultToJSONTyped(value?: AggregateFilterResult | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'RevisedStartTime': value['RevisedStartTime'] == null ? undefined : ((value['RevisedStartTime']).toISOString()),
        'RevisedProcessingInterval': value['RevisedProcessingInterval'],
        'RevisedAggregateConfiguration': AggregateConfigurationToJSON(value['RevisedAggregateConfiguration']),
    };
}

