/* tslint:disable */
/* eslint-disable */
/**
 * OPC UA Web API
 * Provides simple HTTPS based access to an OPC UA server.
 *
 * The version of the OpenAPI document: 1.05.4
 * Contact: office@opcfoundation.org
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { AggregateConfiguration } from './AggregateConfiguration';
import {
    AggregateConfigurationFromJSON,
    AggregateConfigurationFromJSONTyped,
    AggregateConfigurationToJSON,
    AggregateConfigurationToJSONTyped,
} from './AggregateConfiguration';

/**
 * [Link to specification](https://reference.opcfoundation.org/v105/Core/docs/Part4/7.22.4).
 * @export
 * @interface AggregateFilter
 */
export interface AggregateFilter {
    /**
     * 
     * @type {Date}
     * @memberof AggregateFilter
     */
    StartTime?: Date;
    /**
     * 
     * @type {string}
     * @memberof AggregateFilter
     */
    AggregateType?: string;
    /**
     * 
     * @type {number}
     * @memberof AggregateFilter
     */
    ProcessingInterval?: number;
    /**
     * 
     * @type {AggregateConfiguration}
     * @memberof AggregateFilter
     */
    AggregateConfiguration?: AggregateConfiguration;
}

/**
 * Check if a given object implements the AggregateFilter interface.
 */
export function instanceOfAggregateFilter(value: object): value is AggregateFilter {
    return true;
}

export function AggregateFilterFromJSON(json: any): AggregateFilter {
    return AggregateFilterFromJSONTyped(json, false);
}

export function AggregateFilterFromJSONTyped(json: any, ignoreDiscriminator: boolean): AggregateFilter {
    if (json == null) {
        return json;
    }
    return {
        
        'StartTime': json['StartTime'] == null ? undefined : (new Date(json['StartTime'])),
        'AggregateType': json['AggregateType'] == null ? undefined : json['AggregateType'],
        'ProcessingInterval': json['ProcessingInterval'] == null ? undefined : json['ProcessingInterval'],
        'AggregateConfiguration': json['AggregateConfiguration'] == null ? undefined : AggregateConfigurationFromJSON(json['AggregateConfiguration']),
    };
}

export function AggregateFilterToJSON(json: any): AggregateFilter {
    return AggregateFilterToJSONTyped(json, false);
}

export function AggregateFilterToJSONTyped(value?: AggregateFilter | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'StartTime': value['StartTime'] == null ? undefined : ((value['StartTime']).toISOString()),
        'AggregateType': value['AggregateType'],
        'ProcessingInterval': value['ProcessingInterval'],
        'AggregateConfiguration': AggregateConfigurationToJSON(value['AggregateConfiguration']),
    };
}

