/* tslint:disable */
/* eslint-disable */
/**
 * OPC UA Web API
 * Provides simple HTTPS based access to an OPC UA server.
 *
 * The version of the OpenAPI document: 1.05.4
 * Contact: office@opcfoundation.org
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * [Link to specification](https://reference.opcfoundation.org/v105/Core/docs/Part4/5.9.4/#5.9.4.2).
 * @export
 * @interface BrowsePathTarget
 */
export interface BrowsePathTarget {
    /**
     * 
     * @type {string}
     * @memberof BrowsePathTarget
     */
    TargetId?: string;
    /**
     * 
     * @type {number}
     * @memberof BrowsePathTarget
     */
    RemainingPathIndex?: number;
}

/**
 * Check if a given object implements the BrowsePathTarget interface.
 */
export function instanceOfBrowsePathTarget(value: object): value is BrowsePathTarget {
    return true;
}

export function BrowsePathTargetFromJSON(json: any): BrowsePathTarget {
    return BrowsePathTargetFromJSONTyped(json, false);
}

export function BrowsePathTargetFromJSONTyped(json: any, ignoreDiscriminator: boolean): BrowsePathTarget {
    if (json == null) {
        return json;
    }
    return {
        
        'TargetId': json['TargetId'] == null ? undefined : json['TargetId'],
        'RemainingPathIndex': json['RemainingPathIndex'] == null ? undefined : json['RemainingPathIndex'],
    };
}

  export function BrowsePathTargetToJSON(json: any): BrowsePathTarget {
      return BrowsePathTargetToJSONTyped(json, false);
  }

  export function BrowsePathTargetToJSONTyped(value?: BrowsePathTarget | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'TargetId': value['TargetId'],
        'RemainingPathIndex': value['RemainingPathIndex'],
    };
}

