/* tslint:disable */
/* eslint-disable */
/**
 * OPC UA Web API
 * Provides simple HTTPS based access to an OPC UA server.
 *
 * The version of the OpenAPI document: 1.05.4
 * Contact: office@opcfoundation.org
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { Variant } from './Variant';
import {
    VariantFromJSON,
    VariantFromJSONTyped,
    VariantToJSON,
    VariantToJSONTyped,
} from './Variant';
import type { DiagnosticInfo } from './DiagnosticInfo';
import {
    DiagnosticInfoFromJSON,
    DiagnosticInfoFromJSONTyped,
    DiagnosticInfoToJSON,
    DiagnosticInfoToJSONTyped,
} from './DiagnosticInfo';
import type { StatusCode } from './StatusCode';
import {
    StatusCodeFromJSON,
    StatusCodeFromJSONTyped,
    StatusCodeToJSON,
    StatusCodeToJSONTyped,
} from './StatusCode';

/**
 * [Link to specification](https://reference.opcfoundation.org/v105/Core/docs/Part4/5.12.2/#5.12.2.2).
 * @export
 * @interface CallMethodResult
 */
export interface CallMethodResult {
    /**
     * 
     * @type {StatusCode}
     * @memberof CallMethodResult
     */
    StatusCode?: StatusCode;
    /**
     * 
     * @type {Array<StatusCode>}
     * @memberof CallMethodResult
     */
    InputArgumentResults?: Array<StatusCode>;
    /**
     * 
     * @type {Array<DiagnosticInfo>}
     * @memberof CallMethodResult
     */
    InputArgumentDiagnosticInfos?: Array<DiagnosticInfo>;
    /**
     * 
     * @type {Array<Variant>}
     * @memberof CallMethodResult
     */
    OutputArguments?: Array<Variant>;
}

/**
 * Check if a given object implements the CallMethodResult interface.
 */
export function instanceOfCallMethodResult(value: object): value is CallMethodResult {
    return true;
}

export function CallMethodResultFromJSON(json: any): CallMethodResult {
    return CallMethodResultFromJSONTyped(json, false);
}

export function CallMethodResultFromJSONTyped(json: any, ignoreDiscriminator: boolean): CallMethodResult {
    if (json == null) {
        return json;
    }
    return {
        
        'StatusCode': json['StatusCode'] == null ? undefined : StatusCodeFromJSON(json['StatusCode']),
        'InputArgumentResults': json['InputArgumentResults'] == null ? undefined : ((json['InputArgumentResults'] as Array<any>).map(StatusCodeFromJSON)),
        'InputArgumentDiagnosticInfos': json['InputArgumentDiagnosticInfos'] == null ? undefined : ((json['InputArgumentDiagnosticInfos'] as Array<any>).map(DiagnosticInfoFromJSON)),
        'OutputArguments': json['OutputArguments'] == null ? undefined : ((json['OutputArguments'] as Array<any>).map(VariantFromJSON)),
    };
}

export function CallMethodResultToJSON(json: any): CallMethodResult {
    return CallMethodResultToJSONTyped(json, false);
}

export function CallMethodResultToJSONTyped(value?: CallMethodResult | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'StatusCode': StatusCodeToJSON(value['StatusCode']),
        'InputArgumentResults': value['InputArgumentResults'] == null ? undefined : ((value['InputArgumentResults'] as Array<any>).map(StatusCodeToJSON)),
        'InputArgumentDiagnosticInfos': value['InputArgumentDiagnosticInfos'] == null ? undefined : ((value['InputArgumentDiagnosticInfos'] as Array<any>).map(DiagnosticInfoToJSON)),
        'OutputArguments': value['OutputArguments'] == null ? undefined : ((value['OutputArguments'] as Array<any>).map(VariantToJSON)),
    };
}

