/* tslint:disable */
/* eslint-disable */
/**
 * OPC UA Web API
 * Provides simple HTTPS based access to an OPC UA server.
 *
 * The version of the OpenAPI document: 1.05.4
 * Contact: office@opcfoundation.org
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { ResponseHeader } from './ResponseHeader';
import {
    ResponseHeaderFromJSON,
    ResponseHeaderFromJSONTyped,
    ResponseHeaderToJSON,
    ResponseHeaderToJSONTyped,
} from './ResponseHeader';
import type { CallMethodResult } from './CallMethodResult';
import {
    CallMethodResultFromJSON,
    CallMethodResultFromJSONTyped,
    CallMethodResultToJSON,
    CallMethodResultToJSONTyped,
} from './CallMethodResult';
import type { DiagnosticInfo } from './DiagnosticInfo';
import {
    DiagnosticInfoFromJSON,
    DiagnosticInfoFromJSONTyped,
    DiagnosticInfoToJSON,
    DiagnosticInfoToJSONTyped,
} from './DiagnosticInfo';

/**
 * [Link to specification](https://reference.opcfoundation.org/v105/Core/docs/Part4/5.12.2/#5.12.2.2).
 * @export
 * @interface CallResponse
 */
export interface CallResponse {
    /**
     * 
     * @type {ResponseHeader}
     * @memberof CallResponse
     */
    ResponseHeader?: ResponseHeader;
    /**
     * 
     * @type {Array<CallMethodResult>}
     * @memberof CallResponse
     */
    Results?: Array<CallMethodResult>;
    /**
     * 
     * @type {Array<DiagnosticInfo>}
     * @memberof CallResponse
     */
    DiagnosticInfos?: Array<DiagnosticInfo>;
}

/**
 * Check if a given object implements the CallResponse interface.
 */
export function instanceOfCallResponse(value: object): value is CallResponse {
    return true;
}

export function CallResponseFromJSON(json: any): CallResponse {
    return CallResponseFromJSONTyped(json, false);
}

export function CallResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): CallResponse {
    if (json == null) {
        return json;
    }
    return {
        
        'ResponseHeader': json['ResponseHeader'] == null ? undefined : ResponseHeaderFromJSON(json['ResponseHeader']),
        'Results': json['Results'] == null ? undefined : ((json['Results'] as Array<any>).map(CallMethodResultFromJSON)),
        'DiagnosticInfos': json['DiagnosticInfos'] == null ? undefined : ((json['DiagnosticInfos'] as Array<any>).map(DiagnosticInfoFromJSON)),
    };
}

  export function CallResponseToJSON(json: any): CallResponse {
      return CallResponseToJSONTyped(json, false);
  }

  export function CallResponseToJSONTyped(value?: CallResponse | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'ResponseHeader': ResponseHeaderToJSON(value['ResponseHeader']),
        'Results': value['Results'] == null ? undefined : ((value['Results'] as Array<any>).map(CallMethodResultToJSON)),
        'DiagnosticInfos': value['DiagnosticInfos'] == null ? undefined : ((value['DiagnosticInfos'] as Array<any>).map(DiagnosticInfoToJSON)),
    };
}

