/* tslint:disable */
/* eslint-disable */
/**
 * OPC UA Web API
 * Provides simple HTTPS based access to an OPC UA server.
 *
 * The version of the OpenAPI document: 1.05.4
 * Contact: office@opcfoundation.org
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * [Link to specification](https://reference.opcfoundation.org/v105/Core/docs/Part14/6.2.4/#6.2.4.2).
 * @export
 */
export const DataSetFieldContentMaskBits = {
    StatusCode: 1,
    SourceTimestamp: 2,
    ServerTimestamp: 4,
    SourcePicoSeconds: 8,
    ServerPicoSeconds: 16,
    RawData: 32
} as const;
export type DataSetFieldContentMaskBits = typeof DataSetFieldContentMaskBits[keyof typeof DataSetFieldContentMaskBits];


export function instanceOfDataSetFieldContentMaskBits(value: any): boolean {
    for (const key in DataSetFieldContentMaskBits) {
        if (Object.prototype.hasOwnProperty.call(DataSetFieldContentMaskBits, key)) {
            if (DataSetFieldContentMaskBits[key as keyof typeof DataSetFieldContentMaskBits] === value) {
                return true;
            }
        }
    }
    return false;
}

export function DataSetFieldContentMaskBitsFromJSON(json: any): DataSetFieldContentMaskBits {
    return DataSetFieldContentMaskBitsFromJSONTyped(json, false);
}

export function DataSetFieldContentMaskBitsFromJSONTyped(json: any, ignoreDiscriminator: boolean): DataSetFieldContentMaskBits {
    return json as DataSetFieldContentMaskBits;
}

export function DataSetFieldContentMaskBitsToJSON(value?: DataSetFieldContentMaskBits | null): any {
    return value as any;
}

export function DataSetFieldContentMaskBitsToJSONTyped(value: any, ignoreDiscriminator: boolean): DataSetFieldContentMaskBits {
    return value as DataSetFieldContentMaskBits;
}

