/* tslint:disable */
/* eslint-disable */
/**
 * OPC UA Web API
 * Provides simple HTTPS based access to an OPC UA server.
 *
 * The version of the OpenAPI document: 1.05.4
 * Contact: office@opcfoundation.org
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * [Link to specification](https://reference.opcfoundation.org/v105/Core/docs/Part4/7.10).
 * @export
 */
export const DataChangeTrigger = {
    Status: 0,
    StatusValue: 1,
    StatusValueTimestamp: 2
} as const;
export type DataChangeTrigger = typeof DataChangeTrigger[keyof typeof DataChangeTrigger];


export function instanceOfDataChangeTrigger(value: any): boolean {
    for (const key in DataChangeTrigger) {
        if (Object.prototype.hasOwnProperty.call(DataChangeTrigger, key)) {
            if (DataChangeTrigger[key as keyof typeof DataChangeTrigger] === value) {
                return true;
            }
        }
    }
    return false;
}

export function DataChangeTriggerFromJSON(json: any): DataChangeTrigger {
    return DataChangeTriggerFromJSONTyped(json, false);
}

export function DataChangeTriggerFromJSONTyped(json: any, ignoreDiscriminator: boolean): DataChangeTrigger {
    return json as DataChangeTrigger;
}

export function DataChangeTriggerToJSON(value?: DataChangeTrigger | null): any {
    return value as any;
}

export function DataChangeTriggerToJSONTyped(value: any, ignoreDiscriminator: boolean): DataChangeTrigger {
    return value as DataChangeTrigger;
}

