/* tslint:disable */
/* eslint-disable */
/**
 * OPC UA Web API
 * Provides simple HTTPS based access to an OPC UA server.
 *
 * The version of the OpenAPI document: 1.05.4
 * Contact: office@opcfoundation.org
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * [Link to specification](https://reference.opcfoundation.org/Core/Part6/v105/docs/5.4.3).
 * @export
 * @interface Decimal
 */
export interface Decimal {
    /**
     * 
     * @type {number}
     * @memberof Decimal
     */
    Scale?: number;
    /**
     * 
     * @type {string}
     * @memberof Decimal
     */
    Value?: string;
}

/**
 * Check if a given object implements the Decimal interface.
 */
export function instanceOfDecimal(value: object): value is Decimal {
    return true;
}

export function DecimalFromJSON(json: any): Decimal {
    return DecimalFromJSONTyped(json, false);
}

export function DecimalFromJSONTyped(json: any, ignoreDiscriminator: boolean): Decimal {
    if (json == null) {
        return json;
    }
    return {
        
        'Scale': json['Scale'] == null ? undefined : json['Scale'],
        'Value': json['Value'] == null ? undefined : json['Value'],
    };
}

export function DecimalToJSON(json: any): Decimal {
    return DecimalToJSONTyped(json, false);
}

export function DecimalToJSONTyped(value?: Decimal | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'Scale': value['Scale'],
        'Value': value['Value'],
    };
}

