/* tslint:disable */
/* eslint-disable */
/**
 * OPC UA Web API
 * Provides simple HTTPS based access to an OPC UA server.
 *
 * The version of the OpenAPI document: 1.05.4
 * Contact: office@opcfoundation.org
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * [Link to specification](https://reference.opcfoundation.org/specs/OPC-10000-4/v1.05.07/5.8.4).
 * @export
 * @interface DeleteNodesItem
 */
export interface DeleteNodesItem {
    /**
     * 
     * @type {string}
     * @memberof DeleteNodesItem
     */
    NodeId?: string;
    /**
     * 
     * @type {boolean}
     * @memberof DeleteNodesItem
     */
    DeleteTargetReferences?: boolean;
}

/**
 * Check if a given object implements the DeleteNodesItem interface.
 */
export function instanceOfDeleteNodesItem(value: object): value is DeleteNodesItem {
    return true;
}

export function DeleteNodesItemFromJSON(json: any): DeleteNodesItem {
    return DeleteNodesItemFromJSONTyped(json, false);
}

export function DeleteNodesItemFromJSONTyped(json: any, ignoreDiscriminator: boolean): DeleteNodesItem {
    if (json == null) {
        return json;
    }
    return {
        
        'NodeId': json['NodeId'] == null ? undefined : json['NodeId'],
        'DeleteTargetReferences': json['DeleteTargetReferences'] == null ? undefined : json['DeleteTargetReferences'],
    };
}

export function DeleteNodesItemToJSON(json: any): DeleteNodesItem {
    return DeleteNodesItemToJSONTyped(json, false);
}

export function DeleteNodesItemToJSONTyped(value?: DeleteNodesItem | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'NodeId': value['NodeId'],
        'DeleteTargetReferences': value['DeleteTargetReferences'],
    };
}

