/* tslint:disable */
/* eslint-disable */
/**
 * OPC UA Web API
 * Provides simple HTTPS based access to an OPC UA server.
 *
 * The version of the OpenAPI document: 1.05.4
 * Contact: office@opcfoundation.org
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { DeleteNodesItem } from './DeleteNodesItem';
import {
    DeleteNodesItemFromJSON,
    DeleteNodesItemFromJSONTyped,
    DeleteNodesItemToJSON,
    DeleteNodesItemToJSONTyped,
} from './DeleteNodesItem';
import type { RequestHeader } from './RequestHeader';
import {
    RequestHeaderFromJSON,
    RequestHeaderFromJSONTyped,
    RequestHeaderToJSON,
    RequestHeaderToJSONTyped,
} from './RequestHeader';

/**
 * [Link to specification](https://reference.opcfoundation.org/specs/OPC-10000-4/v1.05.07/5.8.4).
 * @export
 * @interface DeleteNodesRequest
 */
export interface DeleteNodesRequest {
    /**
     * 
     * @type {RequestHeader}
     * @memberof DeleteNodesRequest
     */
    RequestHeader?: RequestHeader;
    /**
     * 
     * @type {Array<DeleteNodesItem>}
     * @memberof DeleteNodesRequest
     */
    NodesToDelete?: Array<DeleteNodesItem>;
}

/**
 * Check if a given object implements the DeleteNodesRequest interface.
 */
export function instanceOfDeleteNodesRequest(value: object): value is DeleteNodesRequest {
    return true;
}

export function DeleteNodesRequestFromJSON(json: any): DeleteNodesRequest {
    return DeleteNodesRequestFromJSONTyped(json, false);
}

export function DeleteNodesRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): DeleteNodesRequest {
    if (json == null) {
        return json;
    }
    return {
        
        'RequestHeader': json['RequestHeader'] == null ? undefined : RequestHeaderFromJSON(json['RequestHeader']),
        'NodesToDelete': json['NodesToDelete'] == null ? undefined : ((json['NodesToDelete'] as Array<any>).map(DeleteNodesItemFromJSON)),
    };
}

export function DeleteNodesRequestToJSON(json: any): DeleteNodesRequest {
    return DeleteNodesRequestToJSONTyped(json, false);
}

export function DeleteNodesRequestToJSONTyped(value?: DeleteNodesRequest | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'RequestHeader': RequestHeaderToJSON(value['RequestHeader']),
        'NodesToDelete': value['NodesToDelete'] == null ? undefined : ((value['NodesToDelete'] as Array<any>).map(DeleteNodesItemToJSON)),
    };
}

