/* tslint:disable */
/* eslint-disable */
/**
 * OPC UA Web API
 * Provides simple HTTPS based access to an OPC UA server.
 *
 * The version of the OpenAPI document: 1.05.4
 * Contact: office@opcfoundation.org
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { RequestHeader } from './RequestHeader';
import {
    RequestHeaderFromJSON,
    RequestHeaderFromJSONTyped,
    RequestHeaderToJSON,
    RequestHeaderToJSONTyped,
} from './RequestHeader';

/**
 * [Link to specification](https://reference.opcfoundation.org/v105/Core/docs/Part4/5.14.8/#5.14.8.2).
 * @export
 * @interface DeleteSubscriptionsRequest
 */
export interface DeleteSubscriptionsRequest {
    /**
     * 
     * @type {RequestHeader}
     * @memberof DeleteSubscriptionsRequest
     */
    RequestHeader?: RequestHeader;
    /**
     * 
     * @type {Array<number>}
     * @memberof DeleteSubscriptionsRequest
     */
    SubscriptionIds?: Array<number>;
}

/**
 * Check if a given object implements the DeleteSubscriptionsRequest interface.
 */
export function instanceOfDeleteSubscriptionsRequest(value: object): value is DeleteSubscriptionsRequest {
    return true;
}

export function DeleteSubscriptionsRequestFromJSON(json: any): DeleteSubscriptionsRequest {
    return DeleteSubscriptionsRequestFromJSONTyped(json, false);
}

export function DeleteSubscriptionsRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): DeleteSubscriptionsRequest {
    if (json == null) {
        return json;
    }
    return {
        
        'RequestHeader': json['RequestHeader'] == null ? undefined : RequestHeaderFromJSON(json['RequestHeader']),
        'SubscriptionIds': json['SubscriptionIds'] == null ? undefined : json['SubscriptionIds'],
    };
}

  export function DeleteSubscriptionsRequestToJSON(json: any): DeleteSubscriptionsRequest {
      return DeleteSubscriptionsRequestToJSONTyped(json, false);
  }

  export function DeleteSubscriptionsRequestToJSONTyped(value?: DeleteSubscriptionsRequest | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'RequestHeader': RequestHeaderToJSON(value['RequestHeader']),
        'SubscriptionIds': value['SubscriptionIds'],
    };
}

