/* tslint:disable */
/* eslint-disable */
/**
 * OPC UA Web API
 * Provides simple HTTPS based access to an OPC UA server.
 *
 * The version of the OpenAPI document: 1.05.4
 * Contact: office@opcfoundation.org
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * [Link to specification](https://reference.opcfoundation.org/v105/Core/docs/Part4/7.7.3).
 * @export
 */
export const FilterOperator = {
    Equals: 0,
    IsNull: 1,
    GreaterThan: 2,
    LessThan: 3,
    GreaterThanOrEqual: 4,
    LessThanOrEqual: 5,
    Like: 6,
    Not: 7,
    Between: 8,
    InList: 9,
    And: 10,
    Or: 11,
    Cast: 12,
    InView: 13,
    OfType: 14,
    RelatedTo: 15,
    BitwiseAnd: 16,
    BitwiseOr: 17
} as const;
export type FilterOperator = typeof FilterOperator[keyof typeof FilterOperator];


export function instanceOfFilterOperator(value: any): boolean {
    for (const key in FilterOperator) {
        if (Object.prototype.hasOwnProperty.call(FilterOperator, key)) {
            if (FilterOperator[key as keyof typeof FilterOperator] === value) {
                return true;
            }
        }
    }
    return false;
}

export function FilterOperatorFromJSON(json: any): FilterOperator {
    return FilterOperatorFromJSONTyped(json, false);
}

export function FilterOperatorFromJSONTyped(json: any, ignoreDiscriminator: boolean): FilterOperator {
    return json as FilterOperator;
}

export function FilterOperatorToJSON(value?: FilterOperator | null): any {
    return value as any;
}

export function FilterOperatorToJSONTyped(value: any, ignoreDiscriminator: boolean): FilterOperator {
    return value as FilterOperator;
}

