/* tslint:disable */
/* eslint-disable */
/**
 * OPC UA Web API
 * Provides simple HTTPS based access to an OPC UA server.
 *
 * The version of the OpenAPI document: 1.05.4
 * Contact: office@opcfoundation.org
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { ResponseHeader } from './ResponseHeader';
import {
    ResponseHeaderFromJSON,
    ResponseHeaderFromJSONTyped,
    ResponseHeaderToJSON,
    ResponseHeaderToJSONTyped,
} from './ResponseHeader';
import type { ApplicationDescription } from './ApplicationDescription';
import {
    ApplicationDescriptionFromJSON,
    ApplicationDescriptionFromJSONTyped,
    ApplicationDescriptionToJSON,
    ApplicationDescriptionToJSONTyped,
} from './ApplicationDescription';

/**
 * [Link to specification](https://reference.opcfoundation.org/v105/Core/docs/Part4/5.5.2/#5.5.2.2).
 * @export
 * @interface FindServersResponse
 */
export interface FindServersResponse {
    /**
     * 
     * @type {ResponseHeader}
     * @memberof FindServersResponse
     */
    ResponseHeader?: ResponseHeader;
    /**
     * 
     * @type {Array<ApplicationDescription>}
     * @memberof FindServersResponse
     */
    Servers?: Array<ApplicationDescription>;
}

/**
 * Check if a given object implements the FindServersResponse interface.
 */
export function instanceOfFindServersResponse(value: object): value is FindServersResponse {
    return true;
}

export function FindServersResponseFromJSON(json: any): FindServersResponse {
    return FindServersResponseFromJSONTyped(json, false);
}

export function FindServersResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): FindServersResponse {
    if (json == null) {
        return json;
    }
    return {
        
        'ResponseHeader': json['ResponseHeader'] == null ? undefined : ResponseHeaderFromJSON(json['ResponseHeader']),
        'Servers': json['Servers'] == null ? undefined : ((json['Servers'] as Array<any>).map(ApplicationDescriptionFromJSON)),
    };
}

export function FindServersResponseToJSON(json: any): FindServersResponse {
    return FindServersResponseToJSONTyped(json, false);
}

export function FindServersResponseToJSONTyped(value?: FindServersResponse | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'ResponseHeader': ResponseHeaderToJSON(value['ResponseHeader']),
        'Servers': value['Servers'] == null ? undefined : ((value['Servers'] as Array<any>).map(ApplicationDescriptionToJSON)),
    };
}

