/* tslint:disable */
/* eslint-disable */
/**
 * OPC UA Web API
 * Provides simple HTTPS based access to an OPC UA server.
 *
 * The version of the OpenAPI document: 1.05.4
 * Contact: office@opcfoundation.org
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { ResponseHeader } from './ResponseHeader';
import {
    ResponseHeaderFromJSON,
    ResponseHeaderFromJSONTyped,
    ResponseHeaderToJSON,
    ResponseHeaderToJSONTyped,
} from './ResponseHeader';
import type { DiagnosticInfo } from './DiagnosticInfo';
import {
    DiagnosticInfoFromJSON,
    DiagnosticInfoFromJSONTyped,
    DiagnosticInfoToJSON,
    DiagnosticInfoToJSONTyped,
} from './DiagnosticInfo';
import type { HistoryReadResult } from './HistoryReadResult';
import {
    HistoryReadResultFromJSON,
    HistoryReadResultFromJSONTyped,
    HistoryReadResultToJSON,
    HistoryReadResultToJSONTyped,
} from './HistoryReadResult';

/**
 * [Link to specification](https://reference.opcfoundation.org/v105/Core/docs/Part4/5.11.3/#5.11.3.2).
 * @export
 * @interface HistoryReadResponse
 */
export interface HistoryReadResponse {
    /**
     * 
     * @type {ResponseHeader}
     * @memberof HistoryReadResponse
     */
    ResponseHeader?: ResponseHeader;
    /**
     * 
     * @type {Array<HistoryReadResult>}
     * @memberof HistoryReadResponse
     */
    Results?: Array<HistoryReadResult>;
    /**
     * 
     * @type {Array<DiagnosticInfo>}
     * @memberof HistoryReadResponse
     */
    DiagnosticInfos?: Array<DiagnosticInfo>;
}

/**
 * Check if a given object implements the HistoryReadResponse interface.
 */
export function instanceOfHistoryReadResponse(value: object): value is HistoryReadResponse {
    return true;
}

export function HistoryReadResponseFromJSON(json: any): HistoryReadResponse {
    return HistoryReadResponseFromJSONTyped(json, false);
}

export function HistoryReadResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): HistoryReadResponse {
    if (json == null) {
        return json;
    }
    return {
        
        'ResponseHeader': json['ResponseHeader'] == null ? undefined : ResponseHeaderFromJSON(json['ResponseHeader']),
        'Results': json['Results'] == null ? undefined : ((json['Results'] as Array<any>).map(HistoryReadResultFromJSON)),
        'DiagnosticInfos': json['DiagnosticInfos'] == null ? undefined : ((json['DiagnosticInfos'] as Array<any>).map(DiagnosticInfoFromJSON)),
    };
}

  export function HistoryReadResponseToJSON(json: any): HistoryReadResponse {
      return HistoryReadResponseToJSONTyped(json, false);
  }

  export function HistoryReadResponseToJSONTyped(value?: HistoryReadResponse | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'ResponseHeader': ResponseHeaderToJSON(value['ResponseHeader']),
        'Results': value['Results'] == null ? undefined : ((value['Results'] as Array<any>).map(HistoryReadResultToJSON)),
        'DiagnosticInfos': value['DiagnosticInfos'] == null ? undefined : ((value['DiagnosticInfos'] as Array<any>).map(DiagnosticInfoToJSON)),
    };
}

