/* tslint:disable */
/* eslint-disable */
/**
 * OPC UA Web API
 * Provides simple HTTPS based access to an OPC UA server.
 *
 * The version of the OpenAPI document: 1.05.4
 * Contact: office@opcfoundation.org
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { ModificationInfo } from './ModificationInfo';
import {
    ModificationInfoFromJSON,
    ModificationInfoFromJSONTyped,
    ModificationInfoToJSON,
    ModificationInfoToJSONTyped,
} from './ModificationInfo';
import type { DataValue } from './DataValue';
import {
    DataValueFromJSON,
    DataValueFromJSONTyped,
    DataValueToJSON,
    DataValueToJSONTyped,
} from './DataValue';

/**
 * [Link to specification](https://reference.opcfoundation.org/v105/Core/docs/Part11/6.6.3).
 * @export
 * @interface HistoryModifiedData
 */
export interface HistoryModifiedData {
    /**
     * 
     * @type {Array<ModificationInfo>}
     * @memberof HistoryModifiedData
     */
    ModificationInfos?: Array<ModificationInfo>;
    /**
     * 
     * @type {Array<DataValue>}
     * @memberof HistoryModifiedData
     */
    DataValues?: Array<DataValue>;
}

/**
 * Check if a given object implements the HistoryModifiedData interface.
 */
export function instanceOfHistoryModifiedData(value: object): value is HistoryModifiedData {
    return true;
}

export function HistoryModifiedDataFromJSON(json: any): HistoryModifiedData {
    return HistoryModifiedDataFromJSONTyped(json, false);
}

export function HistoryModifiedDataFromJSONTyped(json: any, ignoreDiscriminator: boolean): HistoryModifiedData {
    if (json == null) {
        return json;
    }
    return {
        
        'ModificationInfos': json['ModificationInfos'] == null ? undefined : ((json['ModificationInfos'] as Array<any>).map(ModificationInfoFromJSON)),
        'DataValues': json['DataValues'] == null ? undefined : ((json['DataValues'] as Array<any>).map(DataValueFromJSON)),
    };
}

export function HistoryModifiedDataToJSON(json: any): HistoryModifiedData {
    return HistoryModifiedDataToJSONTyped(json, false);
}

export function HistoryModifiedDataToJSONTyped(value?: HistoryModifiedData | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'ModificationInfos': value['ModificationInfos'] == null ? undefined : ((value['ModificationInfos'] as Array<any>).map(ModificationInfoToJSON)),
        'DataValues': value['DataValues'] == null ? undefined : ((value['DataValues'] as Array<any>).map(DataValueToJSON)),
    };
}

