/* tslint:disable */
/* eslint-disable */
/**
 * OPC UA Web API
 * Provides simple HTTPS based access to an OPC UA server.
 *
 * The version of the OpenAPI document: 1.05.4
 * Contact: office@opcfoundation.org
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * [Link to specification](https://reference.opcfoundation.org/v105/Core/docs/Part14/6.3.2/#6.3.2.1.1).
 * @export
 */
export const JsonNetworkMessageContentMaskBits = {
    NetworkMessageHeader: 1,
    DataSetMessageHeader: 2,
    SingleDataSetMessage: 4,
    PublisherId: 8,
    DataSetClassId: 16,
    ReplyTo: 32,
    WriterGroupName: 64
} as const;
export type JsonNetworkMessageContentMaskBits = typeof JsonNetworkMessageContentMaskBits[keyof typeof JsonNetworkMessageContentMaskBits];


export function instanceOfJsonNetworkMessageContentMaskBits(value: any): boolean {
    for (const key in JsonNetworkMessageContentMaskBits) {
        if (Object.prototype.hasOwnProperty.call(JsonNetworkMessageContentMaskBits, key)) {
            if (JsonNetworkMessageContentMaskBits[key as keyof typeof JsonNetworkMessageContentMaskBits] === value) {
                return true;
            }
        }
    }
    return false;
}

export function JsonNetworkMessageContentMaskBitsFromJSON(json: any): JsonNetworkMessageContentMaskBits {
    return JsonNetworkMessageContentMaskBitsFromJSONTyped(json, false);
}

export function JsonNetworkMessageContentMaskBitsFromJSONTyped(json: any, ignoreDiscriminator: boolean): JsonNetworkMessageContentMaskBits {
    return json as JsonNetworkMessageContentMaskBits;
}

export function JsonNetworkMessageContentMaskBitsToJSON(value?: JsonNetworkMessageContentMaskBits | null): any {
    return value as any;
}

export function JsonNetworkMessageContentMaskBitsToJSONTyped(value: any, ignoreDiscriminator: boolean): JsonNetworkMessageContentMaskBits {
    return value as JsonNetworkMessageContentMaskBits;
}

