/* tslint:disable */
/* eslint-disable */
/**
 * OPC UA Web API
 * Provides simple HTTPS based access to an OPC UA server.
 *
 * The version of the OpenAPI document: 1.05.4
 * Contact: office@opcfoundation.org
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * [Link to specification]().
 * @export
 * @interface JsonNetworkMessage
 */
export interface JsonNetworkMessage {
    /**
     * 
     * @type {string}
     * @memberof JsonNetworkMessage
     */
    MessageId?: string;
    /**
     * 
     * @type {string}
     * @memberof JsonNetworkMessage
     */
    MessageType?: string;
    /**
     * 
     * @type {string}
     * @memberof JsonNetworkMessage
     */
    PublisherId?: string;
    /**
     * 
     * @type {string}
     * @memberof JsonNetworkMessage
     */
    WriterGroupName?: string;
    /**
     * 
     * @type {string}
     * @memberof JsonNetworkMessage
     */
    DataSetClassId?: string;
    /**
     * 
     * @type {any}
     * @memberof JsonNetworkMessage
     */
    Messages?: any | null;
}

/**
 * Check if a given object implements the JsonNetworkMessage interface.
 */
export function instanceOfJsonNetworkMessage(value: object): value is JsonNetworkMessage {
    return true;
}

export function JsonNetworkMessageFromJSON(json: any): JsonNetworkMessage {
    return JsonNetworkMessageFromJSONTyped(json, false);
}

export function JsonNetworkMessageFromJSONTyped(json: any, ignoreDiscriminator: boolean): JsonNetworkMessage {
    if (json == null) {
        return json;
    }
    return {
        
        'MessageId': json['MessageId'] == null ? undefined : json['MessageId'],
        'MessageType': json['MessageType'] == null ? undefined : json['MessageType'],
        'PublisherId': json['PublisherId'] == null ? undefined : json['PublisherId'],
        'WriterGroupName': json['WriterGroupName'] == null ? undefined : json['WriterGroupName'],
        'DataSetClassId': json['DataSetClassId'] == null ? undefined : json['DataSetClassId'],
        'Messages': json['Messages'] == null ? undefined : json['Messages'],
    };
}

  export function JsonNetworkMessageToJSON(json: any): JsonNetworkMessage {
      return JsonNetworkMessageToJSONTyped(json, false);
  }

  export function JsonNetworkMessageToJSONTyped(value?: JsonNetworkMessage | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'MessageId': value['MessageId'],
        'MessageType': value['MessageType'],
        'PublisherId': value['PublisherId'],
        'WriterGroupName': value['WriterGroupName'],
        'DataSetClassId': value['DataSetClassId'],
        'Messages': value['Messages'],
    };
}

