/* tslint:disable */
/* eslint-disable */
/**
 * OPC UA Web API
 * Provides simple HTTPS based access to an OPC UA server.
 *
 * The version of the OpenAPI document: 1.05.4
 * Contact: office@opcfoundation.org
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * [Link to specification](https://reference.opcfoundation.org/Core/Part3/v105/docs/8.5).
 * @export
 * @interface LocalizedText
 */
export interface LocalizedText {
    /**
     * 
     * @type {string}
     * @memberof LocalizedText
     */
    Locale?: string;
    /**
     * 
     * @type {string}
     * @memberof LocalizedText
     */
    Text?: string;
}

/**
 * Check if a given object implements the LocalizedText interface.
 */
export function instanceOfLocalizedText(value: object): value is LocalizedText {
    return true;
}

export function LocalizedTextFromJSON(json: any): LocalizedText {
    return LocalizedTextFromJSONTyped(json, false);
}

export function LocalizedTextFromJSONTyped(json: any, ignoreDiscriminator: boolean): LocalizedText {
    if (json == null) {
        return json;
    }
    return {
        
        'Locale': json['Locale'] == null ? undefined : json['Locale'],
        'Text': json['Text'] == null ? undefined : json['Text'],
    };
}

  export function LocalizedTextToJSON(json: any): LocalizedText {
      return LocalizedTextToJSONTyped(json, false);
  }

  export function LocalizedTextToJSONTyped(value?: LocalizedText | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'Locale': value['Locale'],
        'Text': value['Text'],
    };
}

