/* tslint:disable */
/* eslint-disable */
/**
 * OPC UA Web API
 * Provides simple HTTPS based access to an OPC UA server.
 *
 * The version of the OpenAPI document: 1.05.4
 * Contact: office@opcfoundation.org
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { ResponseHeader } from './ResponseHeader';
import {
    ResponseHeaderFromJSON,
    ResponseHeaderFromJSONTyped,
    ResponseHeaderToJSON,
    ResponseHeaderToJSONTyped,
} from './ResponseHeader';

/**
 * [Link to specification](https://reference.opcfoundation.org/v105/Core/docs/Part4/5.14.3/#5.14.3.2).
 * @export
 * @interface ModifySubscriptionResponse
 */
export interface ModifySubscriptionResponse {
    /**
     * 
     * @type {ResponseHeader}
     * @memberof ModifySubscriptionResponse
     */
    ResponseHeader?: ResponseHeader;
    /**
     * 
     * @type {number}
     * @memberof ModifySubscriptionResponse
     */
    RevisedPublishingInterval?: number;
    /**
     * 
     * @type {number}
     * @memberof ModifySubscriptionResponse
     */
    RevisedLifetimeCount?: number;
    /**
     * 
     * @type {number}
     * @memberof ModifySubscriptionResponse
     */
    RevisedMaxKeepAliveCount?: number;
}

/**
 * Check if a given object implements the ModifySubscriptionResponse interface.
 */
export function instanceOfModifySubscriptionResponse(value: object): value is ModifySubscriptionResponse {
    return true;
}

export function ModifySubscriptionResponseFromJSON(json: any): ModifySubscriptionResponse {
    return ModifySubscriptionResponseFromJSONTyped(json, false);
}

export function ModifySubscriptionResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): ModifySubscriptionResponse {
    if (json == null) {
        return json;
    }
    return {
        
        'ResponseHeader': json['ResponseHeader'] == null ? undefined : ResponseHeaderFromJSON(json['ResponseHeader']),
        'RevisedPublishingInterval': json['RevisedPublishingInterval'] == null ? undefined : json['RevisedPublishingInterval'],
        'RevisedLifetimeCount': json['RevisedLifetimeCount'] == null ? undefined : json['RevisedLifetimeCount'],
        'RevisedMaxKeepAliveCount': json['RevisedMaxKeepAliveCount'] == null ? undefined : json['RevisedMaxKeepAliveCount'],
    };
}

  export function ModifySubscriptionResponseToJSON(json: any): ModifySubscriptionResponse {
      return ModifySubscriptionResponseToJSONTyped(json, false);
  }

  export function ModifySubscriptionResponseToJSONTyped(value?: ModifySubscriptionResponse | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'ResponseHeader': ResponseHeaderToJSON(value['ResponseHeader']),
        'RevisedPublishingInterval': value['RevisedPublishingInterval'],
        'RevisedLifetimeCount': value['RevisedLifetimeCount'],
        'RevisedMaxKeepAliveCount': value['RevisedMaxKeepAliveCount'],
    };
}

