/* tslint:disable */
/* eslint-disable */
/**
 * OPC UA Web API
 * Provides simple HTTPS based access to an OPC UA server.
 *
 * The version of the OpenAPI document: 1.05.4
 * Contact: office@opcfoundation.org
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { ResponseHeader } from './ResponseHeader';
import {
    ResponseHeaderFromJSON,
    ResponseHeaderFromJSONTyped,
    ResponseHeaderToJSON,
    ResponseHeaderToJSONTyped,
} from './ResponseHeader';
import type { MonitoredItemModifyResult } from './MonitoredItemModifyResult';
import {
    MonitoredItemModifyResultFromJSON,
    MonitoredItemModifyResultFromJSONTyped,
    MonitoredItemModifyResultToJSON,
    MonitoredItemModifyResultToJSONTyped,
} from './MonitoredItemModifyResult';
import type { DiagnosticInfo } from './DiagnosticInfo';
import {
    DiagnosticInfoFromJSON,
    DiagnosticInfoFromJSONTyped,
    DiagnosticInfoToJSON,
    DiagnosticInfoToJSONTyped,
} from './DiagnosticInfo';

/**
 * [Link to specification](https://reference.opcfoundation.org/v105/Core/docs/Part4/5.13.3/#5.13.3.2).
 * @export
 * @interface ModifyMonitoredItemsResponse
 */
export interface ModifyMonitoredItemsResponse {
    /**
     * 
     * @type {ResponseHeader}
     * @memberof ModifyMonitoredItemsResponse
     */
    ResponseHeader?: ResponseHeader;
    /**
     * 
     * @type {Array<MonitoredItemModifyResult>}
     * @memberof ModifyMonitoredItemsResponse
     */
    Results?: Array<MonitoredItemModifyResult>;
    /**
     * 
     * @type {Array<DiagnosticInfo>}
     * @memberof ModifyMonitoredItemsResponse
     */
    DiagnosticInfos?: Array<DiagnosticInfo>;
}

/**
 * Check if a given object implements the ModifyMonitoredItemsResponse interface.
 */
export function instanceOfModifyMonitoredItemsResponse(value: object): value is ModifyMonitoredItemsResponse {
    return true;
}

export function ModifyMonitoredItemsResponseFromJSON(json: any): ModifyMonitoredItemsResponse {
    return ModifyMonitoredItemsResponseFromJSONTyped(json, false);
}

export function ModifyMonitoredItemsResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): ModifyMonitoredItemsResponse {
    if (json == null) {
        return json;
    }
    return {
        
        'ResponseHeader': json['ResponseHeader'] == null ? undefined : ResponseHeaderFromJSON(json['ResponseHeader']),
        'Results': json['Results'] == null ? undefined : ((json['Results'] as Array<any>).map(MonitoredItemModifyResultFromJSON)),
        'DiagnosticInfos': json['DiagnosticInfos'] == null ? undefined : ((json['DiagnosticInfos'] as Array<any>).map(DiagnosticInfoFromJSON)),
    };
}

export function ModifyMonitoredItemsResponseToJSON(json: any): ModifyMonitoredItemsResponse {
    return ModifyMonitoredItemsResponseToJSONTyped(json, false);
}

export function ModifyMonitoredItemsResponseToJSONTyped(value?: ModifyMonitoredItemsResponse | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'ResponseHeader': ResponseHeaderToJSON(value['ResponseHeader']),
        'Results': value['Results'] == null ? undefined : ((value['Results'] as Array<any>).map(MonitoredItemModifyResultToJSON)),
        'DiagnosticInfos': value['DiagnosticInfos'] == null ? undefined : ((value['DiagnosticInfos'] as Array<any>).map(DiagnosticInfoToJSON)),
    };
}

