/* tslint:disable */
/* eslint-disable */
/**
 * OPC UA Web API
 * Provides simple HTTPS based access to an OPC UA server.
 *
 * The version of the OpenAPI document: 1.05.4
 * Contact: office@opcfoundation.org
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { ReadValueId } from './ReadValueId';
import {
    ReadValueIdFromJSON,
    ReadValueIdFromJSONTyped,
    ReadValueIdToJSON,
    ReadValueIdToJSONTyped,
} from './ReadValueId';
import type { MonitoringParameters } from './MonitoringParameters';
import {
    MonitoringParametersFromJSON,
    MonitoringParametersFromJSONTyped,
    MonitoringParametersToJSON,
    MonitoringParametersToJSONTyped,
} from './MonitoringParameters';

/**
 * [Link to specification](https://reference.opcfoundation.org/v105/Core/docs/Part4/5.13.2/#5.13.2.2).
 * @export
 * @interface MonitoredItemCreateRequest
 */
export interface MonitoredItemCreateRequest {
    /**
     * 
     * @type {ReadValueId}
     * @memberof MonitoredItemCreateRequest
     */
    ItemToMonitor?: ReadValueId;
    /**
     * [Link to specification](https://reference.opcfoundation.org/v105/Core/docs/Part4/7.23).
     * @type {number}
     * @memberof MonitoredItemCreateRequest
     */
    MonitoringMode?: number;
    /**
     * 
     * @type {MonitoringParameters}
     * @memberof MonitoredItemCreateRequest
     */
    RequestedParameters?: MonitoringParameters;
}

/**
 * Check if a given object implements the MonitoredItemCreateRequest interface.
 */
export function instanceOfMonitoredItemCreateRequest(value: object): value is MonitoredItemCreateRequest {
    return true;
}

export function MonitoredItemCreateRequestFromJSON(json: any): MonitoredItemCreateRequest {
    return MonitoredItemCreateRequestFromJSONTyped(json, false);
}

export function MonitoredItemCreateRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): MonitoredItemCreateRequest {
    if (json == null) {
        return json;
    }
    return {
        
        'ItemToMonitor': json['ItemToMonitor'] == null ? undefined : ReadValueIdFromJSON(json['ItemToMonitor']),
        'MonitoringMode': json['MonitoringMode'] == null ? undefined : json['MonitoringMode'],
        'RequestedParameters': json['RequestedParameters'] == null ? undefined : MonitoringParametersFromJSON(json['RequestedParameters']),
    };
}

export function MonitoredItemCreateRequestToJSON(json: any): MonitoredItemCreateRequest {
    return MonitoredItemCreateRequestToJSONTyped(json, false);
}

export function MonitoredItemCreateRequestToJSONTyped(value?: MonitoredItemCreateRequest | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'ItemToMonitor': ReadValueIdToJSON(value['ItemToMonitor']),
        'MonitoringMode': value['MonitoringMode'],
        'RequestedParameters': MonitoringParametersToJSON(value['RequestedParameters']),
    };
}

