/* tslint:disable */
/* eslint-disable */
/**
 * OPC UA Web API
 * Provides simple HTTPS based access to an OPC UA server.
 *
 * The version of the OpenAPI document: 1.05.4
 * Contact: office@opcfoundation.org
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { ExtensionObject } from './ExtensionObject';
import {
    ExtensionObjectFromJSON,
    ExtensionObjectFromJSONTyped,
    ExtensionObjectToJSON,
    ExtensionObjectToJSONTyped,
} from './ExtensionObject';

/**
 * [Link to specification](https://reference.opcfoundation.org/v105/Core/docs/Part4/7.26).
 * @export
 * @interface NotificationMessage
 */
export interface NotificationMessage {
    /**
     * 
     * @type {number}
     * @memberof NotificationMessage
     */
    SequenceNumber?: number;
    /**
     * 
     * @type {Date}
     * @memberof NotificationMessage
     */
    PublishTime?: Date;
    /**
     * 
     * @type {Array<ExtensionObject>}
     * @memberof NotificationMessage
     */
    NotificationData?: Array<ExtensionObject>;
}

/**
 * Check if a given object implements the NotificationMessage interface.
 */
export function instanceOfNotificationMessage(value: object): value is NotificationMessage {
    return true;
}

export function NotificationMessageFromJSON(json: any): NotificationMessage {
    return NotificationMessageFromJSONTyped(json, false);
}

export function NotificationMessageFromJSONTyped(json: any, ignoreDiscriminator: boolean): NotificationMessage {
    if (json == null) {
        return json;
    }
    return {
        
        'SequenceNumber': json['SequenceNumber'] == null ? undefined : json['SequenceNumber'],
        'PublishTime': json['PublishTime'] == null ? undefined : (new Date(json['PublishTime'])),
        'NotificationData': json['NotificationData'] == null ? undefined : ((json['NotificationData'] as Array<any>).map(ExtensionObjectFromJSON)),
    };
}

  export function NotificationMessageToJSON(json: any): NotificationMessage {
      return NotificationMessageToJSONTyped(json, false);
  }

  export function NotificationMessageToJSONTyped(value?: NotificationMessage | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'SequenceNumber': value['SequenceNumber'],
        'PublishTime': value['PublishTime'] == null ? undefined : ((value['PublishTime']).toISOString()),
        'NotificationData': value['NotificationData'] == null ? undefined : ((value['NotificationData'] as Array<any>).map(ExtensionObjectToJSON)),
    };
}

