/* tslint:disable */
/* eslint-disable */
/**
 * OPC UA Web API
 * Provides simple HTTPS based access to an OPC UA server.
 *
 * The version of the OpenAPI document: 1.05.4
 * Contact: office@opcfoundation.org
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { LocalizedText } from './LocalizedText';
import {
    LocalizedTextFromJSON,
    LocalizedTextFromJSONTyped,
    LocalizedTextToJSON,
    LocalizedTextToJSONTyped,
} from './LocalizedText';

/**
 * [Link to specification](https://reference.opcfoundation.org/v105/Core/docs/Part4/7.2).
 * @export
 * @interface ObjectTypeAttributes
 */
export interface ObjectTypeAttributes {
    /**
     * 
     * @type {boolean}
     * @memberof ObjectTypeAttributes
     */
    IsAbstract?: boolean;
    /**
     * 
     * @type {number}
     * @memberof ObjectTypeAttributes
     */
    SpecifiedAttributes?: number;
    /**
     * 
     * @type {LocalizedText}
     * @memberof ObjectTypeAttributes
     */
    DisplayName?: LocalizedText;
    /**
     * 
     * @type {LocalizedText}
     * @memberof ObjectTypeAttributes
     */
    Description?: LocalizedText;
    /**
     * 
     * @type {number}
     * @memberof ObjectTypeAttributes
     */
    WriteMask?: number;
    /**
     * 
     * @type {number}
     * @memberof ObjectTypeAttributes
     */
    UserWriteMask?: number;
}

/**
 * Check if a given object implements the ObjectTypeAttributes interface.
 */
export function instanceOfObjectTypeAttributes(value: object): value is ObjectTypeAttributes {
    return true;
}

export function ObjectTypeAttributesFromJSON(json: any): ObjectTypeAttributes {
    return ObjectTypeAttributesFromJSONTyped(json, false);
}

export function ObjectTypeAttributesFromJSONTyped(json: any, ignoreDiscriminator: boolean): ObjectTypeAttributes {
    if (json == null) {
        return json;
    }
    return {
        
        'IsAbstract': json['IsAbstract'] == null ? undefined : json['IsAbstract'],
        'SpecifiedAttributes': json['SpecifiedAttributes'] == null ? undefined : json['SpecifiedAttributes'],
        'DisplayName': json['DisplayName'] == null ? undefined : LocalizedTextFromJSON(json['DisplayName']),
        'Description': json['Description'] == null ? undefined : LocalizedTextFromJSON(json['Description']),
        'WriteMask': json['WriteMask'] == null ? undefined : json['WriteMask'],
        'UserWriteMask': json['UserWriteMask'] == null ? undefined : json['UserWriteMask'],
    };
}

export function ObjectTypeAttributesToJSON(json: any): ObjectTypeAttributes {
    return ObjectTypeAttributesToJSONTyped(json, false);
}

export function ObjectTypeAttributesToJSONTyped(value?: ObjectTypeAttributes | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'IsAbstract': value['IsAbstract'],
        'SpecifiedAttributes': value['SpecifiedAttributes'],
        'DisplayName': LocalizedTextToJSON(value['DisplayName']),
        'Description': LocalizedTextToJSON(value['Description']),
        'WriteMask': value['WriteMask'],
        'UserWriteMask': value['UserWriteMask'],
    };
}

