/* tslint:disable */
/* eslint-disable */
/**
 * OPC UA Web API
 * Provides simple HTTPS based access to an OPC UA server.
 *
 * The version of the OpenAPI document: 1.05.4
 * Contact: office@opcfoundation.org
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * [Link to specification](https://reference.opcfoundation.org/v105/Core/docs/Part11/6.8).
 * @export
 */
export const PerformUpdateType = {
    Insert: 1,
    Replace: 2,
    Update: 3,
    Remove: 4
} as const;
export type PerformUpdateType = typeof PerformUpdateType[keyof typeof PerformUpdateType];


export function instanceOfPerformUpdateType(value: any): boolean {
    for (const key in PerformUpdateType) {
        if (Object.prototype.hasOwnProperty.call(PerformUpdateType, key)) {
            if (PerformUpdateType[key as keyof typeof PerformUpdateType] === value) {
                return true;
            }
        }
    }
    return false;
}

export function PerformUpdateTypeFromJSON(json: any): PerformUpdateType {
    return PerformUpdateTypeFromJSONTyped(json, false);
}

export function PerformUpdateTypeFromJSONTyped(json: any, ignoreDiscriminator: boolean): PerformUpdateType {
    return json as PerformUpdateType;
}

export function PerformUpdateTypeToJSON(value?: PerformUpdateType | null): any {
    return value as any;
}

export function PerformUpdateTypeToJSONTyped(value: any, ignoreDiscriminator: boolean): PerformUpdateType {
    return value as PerformUpdateType;
}

