/* tslint:disable */
/* eslint-disable */
/**
 * OPC UA Web API
 * Provides simple HTTPS based access to an OPC UA server.
 *
 * The version of the OpenAPI document: 1.05.4
 * Contact: office@opcfoundation.org
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { PublishedDataSetDataType } from './PublishedDataSetDataType';
import {
    PublishedDataSetDataTypeFromJSON,
    PublishedDataSetDataTypeFromJSONTyped,
    PublishedDataSetDataTypeToJSON,
    PublishedDataSetDataTypeToJSONTyped,
} from './PublishedDataSetDataType';
import type { PubSubConnectionDataType } from './PubSubConnectionDataType';
import {
    PubSubConnectionDataTypeFromJSON,
    PubSubConnectionDataTypeFromJSONTyped,
    PubSubConnectionDataTypeToJSON,
    PubSubConnectionDataTypeToJSONTyped,
} from './PubSubConnectionDataType';

/**
 * [Link to specification](https://reference.opcfoundation.org/v105/Core/docs/Part14/6.2.12/#6.2.12.1).
 * @export
 * @interface PubSubConfigurationDataType
 */
export interface PubSubConfigurationDataType {
    /**
     * 
     * @type {Array<PublishedDataSetDataType>}
     * @memberof PubSubConfigurationDataType
     */
    PublishedDataSets?: Array<PublishedDataSetDataType>;
    /**
     * 
     * @type {Array<PubSubConnectionDataType>}
     * @memberof PubSubConfigurationDataType
     */
    Connections?: Array<PubSubConnectionDataType>;
    /**
     * 
     * @type {boolean}
     * @memberof PubSubConfigurationDataType
     */
    Enabled?: boolean;
}

/**
 * Check if a given object implements the PubSubConfigurationDataType interface.
 */
export function instanceOfPubSubConfigurationDataType(value: object): value is PubSubConfigurationDataType {
    return true;
}

export function PubSubConfigurationDataTypeFromJSON(json: any): PubSubConfigurationDataType {
    return PubSubConfigurationDataTypeFromJSONTyped(json, false);
}

export function PubSubConfigurationDataTypeFromJSONTyped(json: any, ignoreDiscriminator: boolean): PubSubConfigurationDataType {
    if (json == null) {
        return json;
    }
    return {
        
        'PublishedDataSets': json['PublishedDataSets'] == null ? undefined : ((json['PublishedDataSets'] as Array<any>).map(PublishedDataSetDataTypeFromJSON)),
        'Connections': json['Connections'] == null ? undefined : ((json['Connections'] as Array<any>).map(PubSubConnectionDataTypeFromJSON)),
        'Enabled': json['Enabled'] == null ? undefined : json['Enabled'],
    };
}

export function PubSubConfigurationDataTypeToJSON(json: any): PubSubConfigurationDataType {
    return PubSubConfigurationDataTypeToJSONTyped(json, false);
}

export function PubSubConfigurationDataTypeToJSONTyped(value?: PubSubConfigurationDataType | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'PublishedDataSets': value['PublishedDataSets'] == null ? undefined : ((value['PublishedDataSets'] as Array<any>).map(PublishedDataSetDataTypeToJSON)),
        'Connections': value['Connections'] == null ? undefined : ((value['Connections'] as Array<any>).map(PubSubConnectionDataTypeToJSON)),
        'Enabled': value['Enabled'],
    };
}

