/* tslint:disable */
/* eslint-disable */
/**
 * OPC UA Web API
 * Provides simple HTTPS based access to an OPC UA server.
 *
 * The version of the OpenAPI document: 1.05.4
 * Contact: office@opcfoundation.org
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * [Link to specification](https://reference.opcfoundation.org/v105/Core/docs/Part11/6.5.6/#6.5.6.1).
 * @export
 * @interface ReadAnnotationDataDetails
 */
export interface ReadAnnotationDataDetails {
    /**
     * 
     * @type {Array<Date>}
     * @memberof ReadAnnotationDataDetails
     */
    ReqTimes?: Array<Date>;
}

/**
 * Check if a given object implements the ReadAnnotationDataDetails interface.
 */
export function instanceOfReadAnnotationDataDetails(value: object): value is ReadAnnotationDataDetails {
    return true;
}

export function ReadAnnotationDataDetailsFromJSON(json: any): ReadAnnotationDataDetails {
    return ReadAnnotationDataDetailsFromJSONTyped(json, false);
}

export function ReadAnnotationDataDetailsFromJSONTyped(json: any, ignoreDiscriminator: boolean): ReadAnnotationDataDetails {
    if (json == null) {
        return json;
    }
    return {
        
        'ReqTimes': json['ReqTimes'] == null ? undefined : json['ReqTimes'],
    };
}

export function ReadAnnotationDataDetailsToJSON(json: any): ReadAnnotationDataDetails {
    return ReadAnnotationDataDetailsToJSONTyped(json, false);
}

export function ReadAnnotationDataDetailsToJSONTyped(value?: ReadAnnotationDataDetails | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'ReqTimes': value['ReqTimes'],
    };
}

