/* tslint:disable */
/* eslint-disable */
/**
 * OPC UA Web API
 * Provides simple HTTPS based access to an OPC UA server.
 *
 * The version of the OpenAPI document: 1.05.4
 * Contact: office@opcfoundation.org
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { DataSetReaderDataType } from './DataSetReaderDataType';
import {
    DataSetReaderDataTypeFromJSON,
    DataSetReaderDataTypeFromJSONTyped,
    DataSetReaderDataTypeToJSON,
    DataSetReaderDataTypeToJSONTyped,
} from './DataSetReaderDataType';
import type { KeyValuePair } from './KeyValuePair';
import {
    KeyValuePairFromJSON,
    KeyValuePairFromJSONTyped,
    KeyValuePairToJSON,
    KeyValuePairToJSONTyped,
} from './KeyValuePair';
import type { EndpointDescription } from './EndpointDescription';
import {
    EndpointDescriptionFromJSON,
    EndpointDescriptionFromJSONTyped,
    EndpointDescriptionToJSON,
    EndpointDescriptionToJSONTyped,
} from './EndpointDescription';

/**
 * [Link to specification](https://reference.opcfoundation.org/v105/Core/docs/Part14/6.2.8/#6.2.8.2.1).
 * @export
 * @interface ReaderGroupDataType
 */
export interface ReaderGroupDataType {
    /**
     * 
     * @type {object}
     * @memberof ReaderGroupDataType
     */
    TransportSettings?: object;
    /**
     * 
     * @type {object}
     * @memberof ReaderGroupDataType
     */
    MessageSettings?: object;
    /**
     * 
     * @type {Array<DataSetReaderDataType>}
     * @memberof ReaderGroupDataType
     */
    DataSetReaders?: Array<DataSetReaderDataType>;
    /**
     * 
     * @type {string}
     * @memberof ReaderGroupDataType
     */
    Name?: string;
    /**
     * 
     * @type {boolean}
     * @memberof ReaderGroupDataType
     */
    Enabled?: boolean;
    /**
     * [Link to specification](https://reference.opcfoundation.org/v105/Core/docs/Part5/12.3.10).
     * @type {number}
     * @memberof ReaderGroupDataType
     */
    SecurityMode?: number;
    /**
     * 
     * @type {string}
     * @memberof ReaderGroupDataType
     */
    SecurityGroupId?: string;
    /**
     * 
     * @type {Array<EndpointDescription>}
     * @memberof ReaderGroupDataType
     */
    SecurityKeyServices?: Array<EndpointDescription>;
    /**
     * 
     * @type {number}
     * @memberof ReaderGroupDataType
     */
    MaxNetworkMessageSize?: number;
    /**
     * 
     * @type {Array<KeyValuePair>}
     * @memberof ReaderGroupDataType
     */
    GroupProperties?: Array<KeyValuePair>;
}

/**
 * Check if a given object implements the ReaderGroupDataType interface.
 */
export function instanceOfReaderGroupDataType(value: object): value is ReaderGroupDataType {
    return true;
}

export function ReaderGroupDataTypeFromJSON(json: any): ReaderGroupDataType {
    return ReaderGroupDataTypeFromJSONTyped(json, false);
}

export function ReaderGroupDataTypeFromJSONTyped(json: any, ignoreDiscriminator: boolean): ReaderGroupDataType {
    if (json == null) {
        return json;
    }
    return {
        
        'TransportSettings': json['TransportSettings'] == null ? undefined : json['TransportSettings'],
        'MessageSettings': json['MessageSettings'] == null ? undefined : json['MessageSettings'],
        'DataSetReaders': json['DataSetReaders'] == null ? undefined : ((json['DataSetReaders'] as Array<any>).map(DataSetReaderDataTypeFromJSON)),
        'Name': json['Name'] == null ? undefined : json['Name'],
        'Enabled': json['Enabled'] == null ? undefined : json['Enabled'],
        'SecurityMode': json['SecurityMode'] == null ? undefined : json['SecurityMode'],
        'SecurityGroupId': json['SecurityGroupId'] == null ? undefined : json['SecurityGroupId'],
        'SecurityKeyServices': json['SecurityKeyServices'] == null ? undefined : ((json['SecurityKeyServices'] as Array<any>).map(EndpointDescriptionFromJSON)),
        'MaxNetworkMessageSize': json['MaxNetworkMessageSize'] == null ? undefined : json['MaxNetworkMessageSize'],
        'GroupProperties': json['GroupProperties'] == null ? undefined : ((json['GroupProperties'] as Array<any>).map(KeyValuePairFromJSON)),
    };
}

  export function ReaderGroupDataTypeToJSON(json: any): ReaderGroupDataType {
      return ReaderGroupDataTypeToJSONTyped(json, false);
  }

  export function ReaderGroupDataTypeToJSONTyped(value?: ReaderGroupDataType | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'TransportSettings': value['TransportSettings'],
        'MessageSettings': value['MessageSettings'],
        'DataSetReaders': value['DataSetReaders'] == null ? undefined : ((value['DataSetReaders'] as Array<any>).map(DataSetReaderDataTypeToJSON)),
        'Name': value['Name'],
        'Enabled': value['Enabled'],
        'SecurityMode': value['SecurityMode'],
        'SecurityGroupId': value['SecurityGroupId'],
        'SecurityKeyServices': value['SecurityKeyServices'] == null ? undefined : ((value['SecurityKeyServices'] as Array<any>).map(EndpointDescriptionToJSON)),
        'MaxNetworkMessageSize': value['MaxNetworkMessageSize'],
        'GroupProperties': value['GroupProperties'] == null ? undefined : ((value['GroupProperties'] as Array<any>).map(KeyValuePairToJSON)),
    };
}

