/* tslint:disable */
/* eslint-disable */
/**
 * OPC UA Web API
 * Provides simple HTTPS based access to an OPC UA server.
 *
 * The version of the OpenAPI document: 1.05.4
 * Contact: office@opcfoundation.org
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { ResponseHeader } from './ResponseHeader';
import {
    ResponseHeaderFromJSON,
    ResponseHeaderFromJSONTyped,
    ResponseHeaderToJSON,
    ResponseHeaderToJSONTyped,
} from './ResponseHeader';
import type { NotificationMessage } from './NotificationMessage';
import {
    NotificationMessageFromJSON,
    NotificationMessageFromJSONTyped,
    NotificationMessageToJSON,
    NotificationMessageToJSONTyped,
} from './NotificationMessage';

/**
 * [Link to specification](https://reference.opcfoundation.org/v105/Core/docs/Part4/5.14.6/#5.14.6.2).
 * @export
 * @interface RepublishResponse
 */
export interface RepublishResponse {
    /**
     * 
     * @type {ResponseHeader}
     * @memberof RepublishResponse
     */
    ResponseHeader?: ResponseHeader;
    /**
     * 
     * @type {NotificationMessage}
     * @memberof RepublishResponse
     */
    NotificationMessage?: NotificationMessage;
}

/**
 * Check if a given object implements the RepublishResponse interface.
 */
export function instanceOfRepublishResponse(value: object): value is RepublishResponse {
    return true;
}

export function RepublishResponseFromJSON(json: any): RepublishResponse {
    return RepublishResponseFromJSONTyped(json, false);
}

export function RepublishResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): RepublishResponse {
    if (json == null) {
        return json;
    }
    return {
        
        'ResponseHeader': json['ResponseHeader'] == null ? undefined : ResponseHeaderFromJSON(json['ResponseHeader']),
        'NotificationMessage': json['NotificationMessage'] == null ? undefined : NotificationMessageFromJSON(json['NotificationMessage']),
    };
}

  export function RepublishResponseToJSON(json: any): RepublishResponse {
      return RepublishResponseToJSONTyped(json, false);
  }

  export function RepublishResponseToJSONTyped(value?: RepublishResponse | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'ResponseHeader': ResponseHeaderToJSON(value['ResponseHeader']),
        'NotificationMessage': NotificationMessageToJSON(value['NotificationMessage']),
    };
}

