/* tslint:disable */
/* eslint-disable */
/**
 * OPC UA Web API
 * Provides simple HTTPS based access to an OPC UA server.
 *
 * The version of the OpenAPI document: 1.05.4
 * Contact: office@opcfoundation.org
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { RequestHeader } from './RequestHeader';
import {
    RequestHeaderFromJSON,
    RequestHeaderFromJSONTyped,
    RequestHeaderToJSON,
    RequestHeaderToJSONTyped,
} from './RequestHeader';

/**
 * [Link to specification](https://reference.opcfoundation.org/v105/Core/docs/Part4/5.13.4/#5.13.4.2).
 * @export
 * @interface SetMonitoringModeRequest
 */
export interface SetMonitoringModeRequest {
    /**
     * 
     * @type {RequestHeader}
     * @memberof SetMonitoringModeRequest
     */
    RequestHeader?: RequestHeader;
    /**
     * 
     * @type {number}
     * @memberof SetMonitoringModeRequest
     */
    SubscriptionId?: number;
    /**
     * [Link to specification](https://reference.opcfoundation.org/v105/Core/docs/Part4/7.23).
     * @type {number}
     * @memberof SetMonitoringModeRequest
     */
    MonitoringMode?: number;
    /**
     * 
     * @type {Array<number>}
     * @memberof SetMonitoringModeRequest
     */
    MonitoredItemIds?: Array<number>;
}

/**
 * Check if a given object implements the SetMonitoringModeRequest interface.
 */
export function instanceOfSetMonitoringModeRequest(value: object): value is SetMonitoringModeRequest {
    return true;
}

export function SetMonitoringModeRequestFromJSON(json: any): SetMonitoringModeRequest {
    return SetMonitoringModeRequestFromJSONTyped(json, false);
}

export function SetMonitoringModeRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): SetMonitoringModeRequest {
    if (json == null) {
        return json;
    }
    return {
        
        'RequestHeader': json['RequestHeader'] == null ? undefined : RequestHeaderFromJSON(json['RequestHeader']),
        'SubscriptionId': json['SubscriptionId'] == null ? undefined : json['SubscriptionId'],
        'MonitoringMode': json['MonitoringMode'] == null ? undefined : json['MonitoringMode'],
        'MonitoredItemIds': json['MonitoredItemIds'] == null ? undefined : json['MonitoredItemIds'],
    };
}

export function SetMonitoringModeRequestToJSON(json: any): SetMonitoringModeRequest {
    return SetMonitoringModeRequestToJSONTyped(json, false);
}

export function SetMonitoringModeRequestToJSONTyped(value?: SetMonitoringModeRequest | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'RequestHeader': RequestHeaderToJSON(value['RequestHeader']),
        'SubscriptionId': value['SubscriptionId'],
        'MonitoringMode': value['MonitoringMode'],
        'MonitoredItemIds': value['MonitoredItemIds'],
    };
}

