/* tslint:disable */
/* eslint-disable */
/**
 * OPC UA Web API
 * Provides simple HTTPS based access to an OPC UA server.
 *
 * The version of the OpenAPI document: 1.05.4
 * Contact: office@opcfoundation.org
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * [Link to specification](https://reference.opcfoundation.org/v105/Core/docs/Part5/12.35).
 * @export
 * @interface SimpleTypeDescription
 */
export interface SimpleTypeDescription {
    /**
     * 
     * @type {string}
     * @memberof SimpleTypeDescription
     */
    BaseDataType?: string;
    /**
     * 
     * @type {number}
     * @memberof SimpleTypeDescription
     */
    BuiltInType?: number;
    /**
     * 
     * @type {string}
     * @memberof SimpleTypeDescription
     */
    DataTypeId?: string;
    /**
     * 
     * @type {string}
     * @memberof SimpleTypeDescription
     */
    Name?: string;
}

/**
 * Check if a given object implements the SimpleTypeDescription interface.
 */
export function instanceOfSimpleTypeDescription(value: object): value is SimpleTypeDescription {
    return true;
}

export function SimpleTypeDescriptionFromJSON(json: any): SimpleTypeDescription {
    return SimpleTypeDescriptionFromJSONTyped(json, false);
}

export function SimpleTypeDescriptionFromJSONTyped(json: any, ignoreDiscriminator: boolean): SimpleTypeDescription {
    if (json == null) {
        return json;
    }
    return {
        
        'BaseDataType': json['BaseDataType'] == null ? undefined : json['BaseDataType'],
        'BuiltInType': json['BuiltInType'] == null ? undefined : json['BuiltInType'],
        'DataTypeId': json['DataTypeId'] == null ? undefined : json['DataTypeId'],
        'Name': json['Name'] == null ? undefined : json['Name'],
    };
}

export function SimpleTypeDescriptionToJSON(json: any): SimpleTypeDescription {
    return SimpleTypeDescriptionToJSONTyped(json, false);
}

export function SimpleTypeDescriptionToJSONTyped(value?: SimpleTypeDescription | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'BaseDataType': value['BaseDataType'],
        'BuiltInType': value['BuiltInType'],
        'DataTypeId': value['DataTypeId'],
        'Name': value['Name'],
    };
}

