/* tslint:disable */
/* eslint-disable */
/**
 * OPC UA Web API
 * Provides simple HTTPS based access to an OPC UA server.
 *
 * The version of the OpenAPI document: 1.05.4
 * Contact: office@opcfoundation.org
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * [Link to specification](https://reference.opcfoundation.org/v105/Core/docs/Part4/7.42).
 * @export
 * @interface UserTokenPolicy
 */
export interface UserTokenPolicy {
    /**
     * 
     * @type {string}
     * @memberof UserTokenPolicy
     */
    PolicyId?: string;
    /**
     * [Link to specification](https://reference.opcfoundation.org/v105/Core/docs/Part4/7.43).
     * @type {number}
     * @memberof UserTokenPolicy
     */
    TokenType?: number;
    /**
     * 
     * @type {string}
     * @memberof UserTokenPolicy
     */
    IssuedTokenType?: string;
    /**
     * 
     * @type {string}
     * @memberof UserTokenPolicy
     */
    IssuerEndpointUrl?: string;
    /**
     * 
     * @type {string}
     * @memberof UserTokenPolicy
     */
    SecurityPolicyUri?: string;
}

/**
 * Check if a given object implements the UserTokenPolicy interface.
 */
export function instanceOfUserTokenPolicy(value: object): value is UserTokenPolicy {
    return true;
}

export function UserTokenPolicyFromJSON(json: any): UserTokenPolicy {
    return UserTokenPolicyFromJSONTyped(json, false);
}

export function UserTokenPolicyFromJSONTyped(json: any, ignoreDiscriminator: boolean): UserTokenPolicy {
    if (json == null) {
        return json;
    }
    return {
        
        'PolicyId': json['PolicyId'] == null ? undefined : json['PolicyId'],
        'TokenType': json['TokenType'] == null ? undefined : json['TokenType'],
        'IssuedTokenType': json['IssuedTokenType'] == null ? undefined : json['IssuedTokenType'],
        'IssuerEndpointUrl': json['IssuerEndpointUrl'] == null ? undefined : json['IssuerEndpointUrl'],
        'SecurityPolicyUri': json['SecurityPolicyUri'] == null ? undefined : json['SecurityPolicyUri'],
    };
}

  export function UserTokenPolicyToJSON(json: any): UserTokenPolicy {
      return UserTokenPolicyToJSONTyped(json, false);
  }

  export function UserTokenPolicyToJSONTyped(value?: UserTokenPolicy | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'PolicyId': value['PolicyId'],
        'TokenType': value['TokenType'],
        'IssuedTokenType': value['IssuedTokenType'],
        'IssuerEndpointUrl': value['IssuerEndpointUrl'],
        'SecurityPolicyUri': value['SecurityPolicyUri'],
    };
}

