/* tslint:disable */
/* eslint-disable */
/**
 * OPC UA Web API
 * Provides simple HTTPS based access to an OPC UA server.
 *
 * The version of the OpenAPI document: 1.05.4
 * Contact: office@opcfoundation.org
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { DataValue } from './DataValue';
import {
    DataValueFromJSON,
    DataValueFromJSONTyped,
    DataValueToJSON,
    DataValueToJSONTyped,
} from './DataValue';
import type { LocalizedText } from './LocalizedText';
import {
    LocalizedTextFromJSON,
    LocalizedTextFromJSONTyped,
    LocalizedTextToJSON,
    LocalizedTextToJSONTyped,
} from './LocalizedText';

/**
 * [Link to specification](https://reference.opcfoundation.org/v105/Core/docs/Part4/7.2).
 * @export
 * @interface VariableAttributes
 */
export interface VariableAttributes {
    /**
     * 
     * @type {DataValue}
     * @memberof VariableAttributes
     */
    Value?: DataValue;
    /**
     * 
     * @type {string}
     * @memberof VariableAttributes
     */
    DataType?: string;
    /**
     * 
     * @type {number}
     * @memberof VariableAttributes
     */
    ValueRank?: number;
    /**
     * 
     * @type {Array<number>}
     * @memberof VariableAttributes
     */
    ArrayDimensions?: Array<number>;
    /**
     * 
     * @type {number}
     * @memberof VariableAttributes
     */
    AccessLevel?: number;
    /**
     * 
     * @type {number}
     * @memberof VariableAttributes
     */
    UserAccessLevel?: number;
    /**
     * 
     * @type {number}
     * @memberof VariableAttributes
     */
    MinimumSamplingInterval?: number;
    /**
     * 
     * @type {boolean}
     * @memberof VariableAttributes
     */
    Historizing?: boolean;
    /**
     * 
     * @type {number}
     * @memberof VariableAttributes
     */
    SpecifiedAttributes?: number;
    /**
     * 
     * @type {LocalizedText}
     * @memberof VariableAttributes
     */
    DisplayName?: LocalizedText;
    /**
     * 
     * @type {LocalizedText}
     * @memberof VariableAttributes
     */
    Description?: LocalizedText;
    /**
     * 
     * @type {number}
     * @memberof VariableAttributes
     */
    WriteMask?: number;
    /**
     * 
     * @type {number}
     * @memberof VariableAttributes
     */
    UserWriteMask?: number;
}

/**
 * Check if a given object implements the VariableAttributes interface.
 */
export function instanceOfVariableAttributes(value: object): value is VariableAttributes {
    return true;
}

export function VariableAttributesFromJSON(json: any): VariableAttributes {
    return VariableAttributesFromJSONTyped(json, false);
}

export function VariableAttributesFromJSONTyped(json: any, ignoreDiscriminator: boolean): VariableAttributes {
    if (json == null) {
        return json;
    }
    return {
        
        'Value': json['Value'] == null ? undefined : DataValueFromJSON(json['Value']),
        'DataType': json['DataType'] == null ? undefined : json['DataType'],
        'ValueRank': json['ValueRank'] == null ? undefined : json['ValueRank'],
        'ArrayDimensions': json['ArrayDimensions'] == null ? undefined : json['ArrayDimensions'],
        'AccessLevel': json['AccessLevel'] == null ? undefined : json['AccessLevel'],
        'UserAccessLevel': json['UserAccessLevel'] == null ? undefined : json['UserAccessLevel'],
        'MinimumSamplingInterval': json['MinimumSamplingInterval'] == null ? undefined : json['MinimumSamplingInterval'],
        'Historizing': json['Historizing'] == null ? undefined : json['Historizing'],
        'SpecifiedAttributes': json['SpecifiedAttributes'] == null ? undefined : json['SpecifiedAttributes'],
        'DisplayName': json['DisplayName'] == null ? undefined : LocalizedTextFromJSON(json['DisplayName']),
        'Description': json['Description'] == null ? undefined : LocalizedTextFromJSON(json['Description']),
        'WriteMask': json['WriteMask'] == null ? undefined : json['WriteMask'],
        'UserWriteMask': json['UserWriteMask'] == null ? undefined : json['UserWriteMask'],
    };
}

export function VariableAttributesToJSON(json: any): VariableAttributes {
    return VariableAttributesToJSONTyped(json, false);
}

export function VariableAttributesToJSONTyped(value?: VariableAttributes | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'Value': DataValueToJSON(value['Value']),
        'DataType': value['DataType'],
        'ValueRank': value['ValueRank'],
        'ArrayDimensions': value['ArrayDimensions'],
        'AccessLevel': value['AccessLevel'],
        'UserAccessLevel': value['UserAccessLevel'],
        'MinimumSamplingInterval': value['MinimumSamplingInterval'],
        'Historizing': value['Historizing'],
        'SpecifiedAttributes': value['SpecifiedAttributes'],
        'DisplayName': LocalizedTextToJSON(value['DisplayName']),
        'Description': LocalizedTextToJSON(value['Description']),
        'WriteMask': value['WriteMask'],
        'UserWriteMask': value['UserWriteMask'],
    };
}

