/* tslint:disable */
/* eslint-disable */
/**
 * OPC UA Web API
 * Provides simple HTTPS based access to an OPC UA server.
 *
 * The version of the OpenAPI document: 1.05.4
 * Contact: office@opcfoundation.org
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * [Link to specification](https://reference.opcfoundation.org/v105/Core/docs/Part4/7.45).
 * @export
 * @interface ViewDescription
 */
export interface ViewDescription {
    /**
     * 
     * @type {string}
     * @memberof ViewDescription
     */
    ViewId?: string;
    /**
     * 
     * @type {Date}
     * @memberof ViewDescription
     */
    Timestamp?: Date;
    /**
     * 
     * @type {number}
     * @memberof ViewDescription
     */
    ViewVersion?: number;
}

/**
 * Check if a given object implements the ViewDescription interface.
 */
export function instanceOfViewDescription(value: object): value is ViewDescription {
    return true;
}

export function ViewDescriptionFromJSON(json: any): ViewDescription {
    return ViewDescriptionFromJSONTyped(json, false);
}

export function ViewDescriptionFromJSONTyped(json: any, ignoreDiscriminator: boolean): ViewDescription {
    if (json == null) {
        return json;
    }
    return {
        
        'ViewId': json['ViewId'] == null ? undefined : json['ViewId'],
        'Timestamp': json['Timestamp'] == null ? undefined : (new Date(json['Timestamp'])),
        'ViewVersion': json['ViewVersion'] == null ? undefined : json['ViewVersion'],
    };
}

  export function ViewDescriptionToJSON(json: any): ViewDescription {
      return ViewDescriptionToJSONTyped(json, false);
  }

  export function ViewDescriptionToJSONTyped(value?: ViewDescription | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'ViewId': value['ViewId'],
        'Timestamp': value['Timestamp'] == null ? undefined : ((value['Timestamp']).toISOString()),
        'ViewVersion': value['ViewVersion'],
    };
}

