/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech) (7.12.0).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
package org.opcfoundation.webapi.serverapi;

import org.opcfoundation.webapi.model.CreateSubscriptionRequest;
import org.opcfoundation.webapi.model.CreateSubscriptionResponse;
import io.swagger.v3.oas.annotations.Operation;
import io.swagger.v3.oas.annotations.Parameter;
import io.swagger.v3.oas.annotations.media.Content;
import io.swagger.v3.oas.annotations.media.Schema;
import io.swagger.v3.oas.annotations.responses.ApiResponse;
import io.swagger.v3.oas.annotations.tags.Tag;
import org.springframework.http.HttpStatus;
import org.springframework.http.MediaType;
import org.springframework.http.ResponseEntity;
import org.springframework.validation.annotation.Validated;
import org.springframework.web.bind.annotation.*;
import org.springframework.web.context.request.NativeWebRequest;

import jakarta.validation.Valid;

import java.util.Optional;
import java.util.concurrent.CompletableFuture;
import jakarta.annotation.Generated;

@Generated(value = "org.openapitools.codegen.languages.SpringCodegen", comments = "Generator version: 7.12.0")
@Validated
@Tag(name = "createsubscription", description = "the createsubscription API")
public interface CreatesubscriptionApi {

    default Optional<NativeWebRequest> getRequest() {
        return Optional.empty();
    }

    /**
     * POST /createsubscription
     *
     * @param createSubscriptionRequest [Link to specification](https://reference.opcfoundation.org/v105/Core/docs/Part4/5.14.2/#5.14.2.2). (optional)
     * @return [Link to specification](https://reference.opcfoundation.org/v105/Core/docs/Part4/5.14.2/#5.14.2.2). (status code 200)
     */
    @Operation(
        operationId = "createSubscription",
        responses = {
            @ApiResponse(responseCode = "200", description = "[Link to specification](https://reference.opcfoundation.org/v105/Core/docs/Part4/5.14.2/#5.14.2.2).", content = {
                @Content(mediaType = "application/json", schema = @Schema(implementation = CreateSubscriptionResponse.class))
            })
        }
    )
    @RequestMapping(
        method = RequestMethod.POST,
        value = {"/createsubscription", "/{serverUri}/createsubscription"},
        produces = { "application/json" },
        consumes = { "application/json" }
    )
    
    default CompletableFuture<ResponseEntity<CreateSubscriptionResponse>> createSubscription(
            @PathVariable(required = false) String serverUri,
        @Parameter(name = "CreateSubscriptionRequest", description = "[Link to specification](https://reference.opcfoundation.org/v105/Core/docs/Part4/5.14.2/#5.14.2.2).") @Valid @RequestBody(required = false) CreateSubscriptionRequest createSubscriptionRequest
    ) {
        return CompletableFuture.supplyAsync(()-> {
            getRequest().ifPresent(request -> {
                for (MediaType mediaType: MediaType.parseMediaTypes(request.getHeader("Accept"))) {
                    if (mediaType.isCompatibleWith(MediaType.valueOf("application/json"))) {
                        String exampleString = "{ \"RevisedMaxKeepAliveCount\" : 2560717018, \"ResponseHeader\" : { \"StringTable\" : [ \"StringTable\", \"StringTable\" ], \"ServiceResult\" : { \"Symbol\" : \"Symbol\", \"Code\" : 2588772717 }, \"RequestHandle\" : 343953088, \"AdditionalHeader\" : { \"UaTypeId\" : \"UaTypeId\", \"UaEncoding\" : 180, \"UaBody\" : \"UaBody\" }, \"Timestamp\" : \"2000-01-23T04:56:07.000+00:00\", \"ServiceDiagnostics\" : { \"Locale\" : 5, \"AdditionalInfo\" : \"AdditionalInfo\", \"NamespaceUri\" : 5, \"SymbolicId\" : 1, \"LocalizedText\" : 2, \"InnerStatusCode\" : { \"Symbol\" : \"Symbol\", \"Code\" : 2588772717 } } }, \"SubscriptionId\" : 343953088, \"RevisedLifetimeCount\" : 629561881, \"RevisedPublishingInterval\" : 6.027456183070403 }";
                        ApiUtil.setExampleResponse(request, "application/json", exampleString);
                        break;
                    }
                }
            });
            return new ResponseEntity<>(HttpStatus.NOT_IMPLEMENTED);
        }, Runnable::run);

    }

}
